### ISSUE TITLE
How to install epub export and kindle export? f

### ISSUE THREAD

**Issue by Schokolader** [pressbooks/pressbooks#1022]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [ ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing this issue with one of our built-in root or book themes?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
I have installed kindlegen and add the line to the path in the wp-config.php. But I still can't export to kindle. What could that be? 

Do you have detailed informations how to install the epub ckeck on ubuntu server? Unfortunately I did not find something great. 

### System Information

_Replace this section with the contents of the Diagnostics page, available at `https://<yourdomain.tld>/<yourbook>/wp-admin/options.php?page=pressbooks_diagnostics` or via the Diagnostics link in the admin footer. If you are using Pressbooks < 3.9.4, you will have to enter the following information manually:_

Pressbooks: [4.5]
WordPress: [4.9.1]
PHP: [7.2]

_You can get the version of Pressbooks from the readme.txt file in the Pressbooks plugin (usually located at `https://<yourdomain.tld>/wp-content/plugins/pressbooks/readme.txt`) and the version of WordPress from the readme.html file in the WordPress root directory (usually located at `https://<yourdomain.tld>/readme.html`). You can usually get your PHP version from your web host, or by using the [`phpversion()`](http://php.net/manual/en/function.phpversion.php) function._

**Comment by greatislander** [comment]
This is not a bug, but a support request, and as such should be posted to https://discourse.pressbooks.org. But my guess is that you can't export for Kindle because you don't have EpubCheck installed. You'll need to download this file from the EpubCheck releases page: https://github.com/IDPF/epubcheck/releases/download/v4.0.2/epubcheck-4.0.2.zip

Unzip it and place the `epubcheck.jar` file in some appropriate place on your server. You will also need to install Java (I recommend running `sudo apt-get install default-jdk`). Then, you should be able to test your installation with the `--help` flag as per [these instructions](https://github.com/IDPF/epubcheck/wiki/Running#system-prerequisites):

```
$ /usr/bin/java -jar /path/to/epubcheck.jar --help
```

Replace `/path/to` with the path to wherever you put `epubcheck.jar`.

If that works, you can define `PB_EPUBCHECK_COMMAND` to `/usr/bin/java -jar /path/to/epubcheck.jar`, again replacing `/path/to` with the full path to wherever you put `epubcheck.jar`.
