### ISSUE TITLE
Add Sanskrit as a language

### ISSUE THREAD

**Issue by Schokolader** [pressbooks/pressbooks#1023]
Add new language: Add Sanskrit as a language

 Include fonts to support the following languages: Sanskrit

**Comment by greatislander** [comment]
The fonts we use for Hindi support are [Noto Sans Devanagari](https://www.google.com/get/noto/#sans-deva) and [Noto Serif Devanagari](https://www.google.com/get/noto/#serif-deva), which is also used for Sanskrit. So you could select Hindi in _Theme Options_ &rarr; _Global_ &rarr; _Language Support_ to add Devanagari fonts to your book. Since Devanagari script is used for over 60 languages, perhaps we should list Devanagari instead of Hindi in the list of supported languages/scripts?
