### ISSUE TITLE
Importing chapters does not handle licensing, some statii properly

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1091]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Book cloning responds appropriately to various licenses, and we need to ensure that chapter import via the cloning mechanism does too. Chapter import via cloning mechanism should also discard content which is private or password-protected.

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 5.0.0-beta.1
WordPress: 4.9.4
PHP: 7.1

**Comment by connerbw** [comment]
Can you provide an example book where this happens?

The import code calls inits using [\Pressbooks\Cloner::setupSource](https://github.com/pressbooks/pressbooks/blob/aa75269a5c3ee5d369ef3b128028bf49632b96de/inc/class-cloner.php#L313) which then calls [\Pressbooks\Cloner::isBookCloneable](https://github.com/pressbooks/pressbooks/blob/aa75269a5c3ee5d369ef3b128028bf49632b96de/inc/class-cloner.php#L587). It won't clone what it is not allowed to clone.

I think there's a misunderstanding of what's going on in HTML import here. If I use, https://book.pressbooks.com/, which is not licensed for cloning, it falls back to HTML scraper mode. This is because we have one form element for both methods.

**Comment by greatislander** [comment]
I think @zwhpressbooks can clarify further, but there's a table of actual/expected behaviour [here](https://docs.google.com/a/pressbooks.com/spreadsheets/d/1hoI7xs31RxtpJcBVhFnaPSRNa_2EDB4z5aX1N4AbrYE/edit?usp=drive_web).

For books like https://book.pressbooks.com, if the Pressbooks API is found but the license is not permissive, the desired behaviour is to cancel the import and notify the user rather than falling back to the scraper mode.

**Comment by greatislander** [comment]
Closed in #1117 and #1119.
