### ISSUE TITLE
Footnotes not converted in HTML export.

### ISSUE THREAD

**Issue by programmieraffe** [pressbooks/pressbooks#121]
Footnotes ([footnote]) are not converted in HTML export, they're just spans:

    <span class="footnote">...</span>

**Comment by greatislander** [comment]
Hi @programmieraffe, thanks for posting the issue. However, this behaviour is intentional. Footnotes can be displayed in a variety of different ways—chapter-based endnotes, page-based footnotes, endnotes to the entire text—and rather than making a decision about how this will be done within the XHTML export routine, we simply mark up footnotes within the text so that they can be identified and then displayed as desired. This in turn gives us some flexibility within our PDF export module, and allows users to take a Pressbooks-generated (X)HTML file to display it in whatever manner they wish using CSS and Javascript. I hope this clarifies our intentions here. Anything to add, @hughmcguire?

**Comment by programmieraffe** [comment]
Thanks for the explanation! But for non-technical users it would be a great idea to implement a javascript/css-snippet which converts the footnotes.

**Comment by greatislander** [comment]
@programmieraffe I take your point, but the problem remains—how do we implement it? Footnotes at the end of each chapter? At the end of the entire book? Do we number footnotes on a per-chapter basis or a whole-book basis? The idea for the XHTML export is not to be a complete, formatted document but to be structured data that can be the basis for other formats—it's about the content, not the display. Fundamentally the implementation of numbered footnotes linking back to their position in the document is a display question, not a content question, and we have purposefully avoided including CSS/JS with the XHTML export because that file format is not intended to be a display-ready export. Thus, it doesn't support themes, or various theme options like footnote vs. endnote display etc. I hope this makes sense.
