### ISSUE TITLE
Add explicit CC Zero and CC Public Domain license types

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#1331]
### Feature Description

Right now when a user selects Public Domain, the content is licensed CC0. This isn't necessarily correct, as identified by @philbarker [in the forums](https://discourse.pressbooks.org/t/copyright-cc0-and-public-domain/651/2).

### Feature Use Case

New Public Domain works can be licensed CC0 by the creator(s), but existing works from the Public Domain likely need to be licensed with CC Public Domain (as per @philbarker, deceased authors whose work is in the public domain have not explicitly "waived all copyright", which the CC0 license text says that they have).

### Other Notes

Existing books with the Public Domain license selected should be CC Public Domain, while CC0 should be added as a new license option. 

### System Information

Pressbooks: 5.5.0-dev

**Comment by SteelWagstaff** [comment]
Hi Ned--I don't think `CC Public Domain` is a thing necessarily (or a category of license). In the traditional sense, for a work to be in the 'public domain' simply means that its copyright has expired and it is no longer protected. The CC0 license is useful when a rights holder wishes to officially renounce these inherent rights and dedicate a work to the public domain before the legal copyright term expires (nice description of some of the distinctions on the [Public Domain wikipedia page](https://en.wikipedia.org/wiki/Public_domain#Dedicating_works_to_the_public_domain)). All this to say that you may want 2 options: 1) one that that simply says 'Public Domain' or 'No known copyright restrictions' and 2) one that allows rights holders to renounce their copyright or dedicate their work to the public domain before the natural expiration of copyright (i.e. CC0).

**Comment by greatislander** [comment]
Hi @SteelWagstaff, from CC:

> Creative Commons does not recommend [CC0] for works that are already in the public domain worldwide. Instead, please use the [Public Domain Mark](https://creativecommons.org/choose/mark/) for such works.

Refs:

- https://creativecommons.org/choose/zero/
- https://creativecommons.org/choose/mark/

**Comment by SteelWagstaff** [comment]
Yes that link from CC makes good sense to me. The Public Domain mark has no relationship with Creative Commons, however. That's all I was trying to specify. Sorry if I unnecessarily explained something you understood perfectly well--I was just a little confused by the reference to "CC" public domain ...

**Comment by greatislander** [comment]
No worries! The original issue may not have been as clear as it could have been. The intention was to use the Public Domain mark and accompanying text provided by Creative Commons as a separate license option from CC0.

**Comment by SteelWagstaff** [comment]
Perfect. Love the idea.

Please forgive my brevity or any typos. This message was composed on a mobile device.

On Aug 27, 2018, at 5:05 PM, Ned Zimmerman <notifications@github.com<mailto:notifications@github.com>> wrote:


No worries! The original issue may not have been as clear as it could have been. The intention was to use the Public Domain mark and accompanying text provided by Creative Commons as a separate license option from CC0.

**Comment by philbarker** [comment]
Thank you @greatislander & @SteelWagstaff It's great to see such timely progress on this.

I think the only point of clarification I would like to add (with apologies if it's unnecessary) is that neither the PD Mark nor CC0 are (just) licenses. They are primarily statements that no license is necessary, either because no rights exist (PD) or because those rights are waived (CC0). The exception is that for jurisdictions where waiving rights is not an option, CC0 has a license fallback that is intended to have the same effect. 

With that in mind it might be least confusing to do a little more than just add the PD Mark under what is currently shown as a list of licensing options.
1/ change the field label from 'copyright license' to something like 'reuse permission'
2/ make sure the output is sensible if no copyright holder is provided
