### ISSUE TITLE
database error pressbooks publisher theme

### ISSUE THREAD

**Issue by bdolor** [pressbooks/pressbooks#139]
Description: Database errors are showing up in debug.log as queries generated against tables (blog_id) that do not exist. 

![screen shot 2015-06-04 at 9 43 05 am](https://cloud.githubusercontent.com/assets/2048170/7989409/2ad88efc-0a9e-11e5-9c6d-81f3457fd96b.png)
 
To recreate: Network Activate the new 'pressbooks publisher' theme. Go to the root site and activate 'pressbooks publisher' theme. Visit Site. Click on 'My Books'. Watch the console log for queries made against non-existent database tables. 

Related/Relevant Issues: 
- There is a reference to 'pressbooks-publisher-one' [here](https://github.com/pressbooks/pressbooks/blob/dev/includes/pb-catalog.php#L128). This generates an 'internal server error' if you navigate to the my catalogue page and click on any of the cover images. If that `$base_href` value gets updated to 'pressbooks-publisher' it generates a fatal error. 
- Definitely unrelated, but relevant, there are numerous references to 'pressbooks-publisher-one' in the [language file](https://github.com/pressbooks/pressbooks/blob/dev/languages/_pressbooks.pot#L61): 
- Some other strange behaviour, is that the admin menu has mostly disappeared in the admin interface of the root site.

![screen shot 2015-06-04 at 10 00 51 am](https://cloud.githubusercontent.com/assets/2048170/7989833/3138aa36-0aa1-11e5-8966-d2a1fe24ab19.png)

**Comment by greatislander** [comment]
Thanks @bdolor.

1. Will investigate database errors. Thanks for spotting.
2. Reference to `pressbooks-publisher-one`—I will fix this. Missed that one.
3. I need to update the `.pot` file from the plugin source—haven't done that in a while.
4. The minimal admin interface for the root site under Publisher 2.0 is intentional, as per @hughmcguire's specs. We wanted to create something very straightforward for users who don't want to deal with setting up a blog, pages etc. but just want to have an index with some descriptive text and a custom logo (edited via the Appearance -> Customize screen) and the ability to display a catalog of books in the network (books can be opted into appearing in the catalog via the Network Admin Sites table). In our observation, most client sites were not touching any of the default content via the old Pressbooks Publisher theme (so lots of index pages with "Hello World!" on them). The thinking here is that if a user wants to set up a more complex root theme for their network, they can do so and can incorporate the catalog components from the new Pressbooks Publisher, but we are now offering a basic root theme that looks professional with minimal effort from users who are more concerned with the books than the root site. (This is the thinking, eh @hughmcguire?)

**Comment by greatislander** [comment]
Hi @bdolor, testing this on my local site and I'm not getting any of the database errors you are reporting. To clarify—does this happen when you visit the publicly viewable user catalog or the catalog administration interface? (I've removed the `$base_href` variable altogether as it was just being used to allow a relative link to a stylesheet.)

**Comment by bdolor** [comment]
It happens when requesting either the publicly viewable user catalogue page or the admin interface. I dug into this a bit more. My database table `wp_blogs` tells me there are 37 rows, which means there should only be 36 books ( 1 row for the network blog ). The catalogue admin interface page tells me there are 39 entries. I would expect to see it list only 36 entries? Where does the catalogue page get the data to populate the list the books that are available?

**Comment by greatislander** [comment]
So, looks like the issue might be that you have cached data which includes a book that has been deleted. The data seems to be fetched [here](https://github.com/pressbooks/pressbooks/blob/dev/includes/class-pb-catalog.php#L135) and is cached with a 24 hour expiry [here](https://github.com/pressbooks/pressbooks/blob/dev/includes/class-pb-catalog.php#L274). Any change to the catalog (e.g. hiding a book from the catalog, editing the catalog profile) clears the cache. Can you try making such a change and see if the errors persist?

**Comment by bdolor** [comment]
No change. Running the query `SELECT * FROM `wp_pressbooks_catalog` WHERE users_id = 1 AND `deleted` = 0;` directly against the db returns the same: 39 rows. It does tell me that there is/was a disconnect between the event of deleting a book and updating the `wp_pressbooks_catalog` table. Now that I know what to look at, I'll see if I can re-create those conditions, before asking you to spend any more time on it. Thanks @greatislander

**Comment by bdolor** [comment]
okay, so this can be re-created — the conditions necessary to introduce this problem are likely limited to super-admins (who have the ability to delete books). 
1. Create a book. 
2. Add it to your catalogue (Show)
3. Delete the book through My Catalogue -> Network Admin -> Sites (Delete)
4. View My Catalog admin page, look for the deleted book distinguished by a book with no title. 
5. View logs for query against a non-existent book.

**Comment by greatislander** [comment]
Aha, so this must have been a pre-existing bug, as we did not change the catalog mechanism with the updated theme—thanks for catching. I'll look for a solution.

**Comment by greatislander** [comment]
Hi @bdolor, let me know if e77b8db fixed it for you. It did for me.

**Comment by bdolor** [comment]
Yes! Fixed. Thank you @greatislander
