### ISSUE TITLE
Including fonts in epub exports

### ISSUE THREAD

**Issue by gigifrias** [pressbooks/pressbooks#150]
We are creating foreign language eBooks and have set up our own hosted instance of Pressbooks.

In creating our publications in the past (prior to discovering Pressbooks), we have found that embedding the open-source fonts used for foreign languages with different character sets (e.g. Cyrillic, Chinese) is crucial to guarantee full support across platforms and e-readers. 

Have you considered allowing users the option to copy some (or all) files from the 'fonts' directory into an ePub during export? I understand the ramifications of embedding licensed fonts, but it could be an option with open-source and purchased fonts.

**Comment by greatislander** [comment]
Thanks for the inquiry, @gigifrias. Thoughts, @hughmcguire?

**Comment by hughmcguire** [comment]
to embed a font in your EPUB ... you should:
declare the font as such in the  EPUB CSS:
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 200;
  src: url(../../../fonts/Lato-Hairline.ttf) format("truetype"); }

I believe your fonts folder should be in:
`~/wp-content/themes/fonts/`

check the paths though -- this is how we do it in Pressbooks.com, but you may be using a different folder for themes in an open source pressbooks install.

**Comment by greatislander** [comment]
@gigifrias Please let us know if this solved your issue.

**Comment by gigifrias** [comment]
Thanks for answering my question, @hughmcguire! We are already embedding fonts in the way suggested, however, when we export to epub it doesn't create a directory for fonts within it. So, declaring a font in the CSS becomes moot once the epub is created. 

What I really wanted to know is whether this is something that you decided to do on purpose and, if so, why.

**Comment by hughmcguire** [comment]
well, we did do it & do do it! 
check the ~/assets/ folder? 

you may have the paths wrong though...  since the open source themes are not in the themes folder...

try adding a /fonts/ folder to ~/themes-book/ and add your fonts there... then (i think) the path to the fonts should work.

**Comment by hughmcguire** [comment]
clarification: the embedded fonts should get stuffed in /assets/

**Comment by gigifrias** [comment]
Hmm, that is interesting. I'll try your suggestions! Thanks again for being so quick to respond.

**Comment by jflowers45** [comment]
Gigi and I actually work together ... we looked through this and ultimately there were a few things in play but we were able to make it work.  

Adding to /themes-book/fonts works with the following caveats:

1)  Your font declaration must reference it using  url(../../../) per this regex https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/epub/class-pb-epub201.php#L610

2)  You must be editing /themes-book/[themename]/export/epub/style.css as opposed to /themes-book/[themename]/style.css 

3)  epub 3 export isn't yet updated for that fonts folder - makes sense since it's still in beta, but presumably the same change will apply there? https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/epub3/class-pb-epub3.php#L264


======INTERNATIONAL SUPPORT ISSUES======== 
4)  That regex assumes numbers/latin letters as filenames and we have some fonts that use international characters.  We have some fonts that don't, so we had to make it a bit more generic to catch those (we just check for *.otf or *.ttf)

5)  PCLZip doesn't work well with international characters in filenames either (we're testing Chinese in specific).  They offer a hook (http://www.phpconcept.net/pclzip/user-guide/50) and the common workaround is to change filename encoding there, but it still wasn't working right.  Tried ZipArchive as well and had same issue. So, we tried running zip as a shell command using exec() from php and that seemed to get the job done.
