### ISSUE TITLE
problems with redirection

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#161]
i have my installation in

http://test.com/

in the main page, if i want to go to the admin page and i push the ADMIN buttom, the page make the redirection to  http://test.com/wordpress/wp-admin

**Comment by greatislander** [comment]
The fact that the admin button takes you to `/wordpress/wp-admin` suggests that your root site is *not* in fact at http://test.com. So that I can troubleshoot this, can you please copy and paste your `.htaccess` file below, and also copy and paste the section of your `wp-config.php` file that looks like this below:

```
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
$base = '/';
define('DOMAIN_CURRENT_SITE', 'test.com');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
```

If you have not correctly configured WordPress multisite as per the [readme](https://github.com/pressbooks/pressbooks/blob/dev/readme.txt) that is likely the problem.

**Comment by colomet** [comment]
i have been using PressBooks since a few months ago, we have several installations and it happen just with the version 2.5.

I unistall the 2.5 version and i still using the version 2.4.5.

but that is my wp-cofig
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
define('DOMAIN_CURRENT_SITE', 'ocw.developer.trash.on-lingua.com');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);

i dont´know what is $base ='/'; from your example


and htacces

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
RewriteRule . index.php [L]

</IfModule>

# END WordPress



thanks
