### ISSUE TITLE
Testing environment doesn't show all error reports on newly updated export page 

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks#1623]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
Error reports are not appearing on the export page for any book exported on Textopress. There are two scenarios: 
1. The error warning does not display on the export page but _does_ get flagged in the mailed error logs. This includes scenario includes SASS errors and footnote errors.
2. The error warning does not display on the export page and does not get flagged in mailed error logs. This includes EPUB CSS errors. 

### Steps to Reproduce

1. Visit Textopress
2. Export a book with an issue that should create an error (ex: extra { in the CSS)
3. Check for a warning banner 

**Expected behavior:** Export page should show a warning banner at the top that lets users know that their files couldn't validate or contain errors. 

**Actual behavior:** No warning banner shows, and users do not know whether or not their files contain errors.

**Comment by connerbw** [comment]
+ Textopress is running epucheck 4.0.2
+ Pressbooks dot com is running epucheck 4.1.0
+ The error that prompted this bug report [is fixed in epucheck 4.1.1](https://github.com/w3c/epubcheck/issues/922)

The issue was not so much that errors weren't being reported on textopress, but different versions of 3rd party software reports different errors.  Textopress had nothing to report because it's fallen behind the latest epucheck. Pressbooks is reporting false positives because, it too, has fallen behind epucheck.

We need to sync epubcheck to the same versions, everywhere.

Closing as "no bug". Will fix this problem as part of operations.
