### ISSUE TITLE
Subscriber are not able to read private chapters in public books.

### ISSUE THREAD

**Issue by marcusschiesser** [pressbooks/pressbooks#174]
Thank you for fixing bug https://github.com/pressbooks/pressbooks/issues/130. Now chapters are displayed in the TOC for users with role 'Subscriber' or higher. But a user needs at least the role 'Editor' to view a chapter. My expectation would be to view a chapter already with 'Subscriber' rights (as it is the case with private books).
In my case, if I am clicking in the TOC at a private chapter, I get redirected to the root page of the site.
I tested this with two different books. I am using pressbooks 2.5

**Comment by greatislander** [comment]
Hi @marcusschiesser, thanks for noting this. Private front matter, chapters and back matter conform to [WordPress conventions](https://codex.wordpress.org/Content_Visibility#Private_Content) regarding private content:

> Private posts are automatically published but not visible to anyone but those with the appropriate permission levels (Editor or Administrator).

If a book is private, users who are added to that book at Subscriber or above will be able to view all content, but not content specifically designated as private within the book. Likewise, no one who is not an Editor or Administrator of a public book will be able to view content specifically designated as private. If you want your book to be private but fully visible to subscribers, you don't need to make each chapter private as well. I have adjusted the TOC and navigation so that users without the permissions required to view private content don't see it in the TOC or have the option to navigate to it (https://github.com/pressbooks/pressbooks/commit/d44ef0ac8caae3a4456d7f87ef66478a261f5d7f).

**Comment by marcusschiesser** [comment]
Ok @greatislander, I see your point. Nevertheless I have a use case where I want some of the chapters only visible to subscribers and all other chapters should be public visible.
Therefore I added feature request #176 , which I would like to implement. Please let me know.
