### ISSUE TITLE
[Research] Investigate feasibility of adding an a11y checker button to TinyMCE visual editor

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1766]
To do (for research task): investigate one or both of the Tiny-MCE based plugins (described here:  https://github.com/pressbooks/ideas/issues/198) that claim to provide a11y checking features for content producers using the visual editor. Research does not involve implementation, but should result in answers to the following questions: 
1. Could one both of these options be integrated with Pressbooks?
1. If so, can we provide a rough effort estimation for doing so?
1. If implemented, what drawbacks/unintended consequences do you foresee? 
1. Would you recommend implementing one over the other, or choosing neither (with brief justification)?

**Comment by connerbw** [comment]
TinyMCE A11ychecker [1] is a Premium Plugin. A TinyMCE Enterprise subscription includes the ability to download it. 

Two types of subscription plans are available. The 1st is cloud subscription [2] and is priced by "editor loads". This implies that the editor is hosted elsewhere. The 2nd is server subscription. It starts at $400 per month for 1 server, $1280 per month for 4 servers, and "Contact us!" for more. 

The cloud option is unfeasible because WordPress bundles their own customized, modified TinyMCE, that Pressbooks in turn customizes [3]. Swapping it out entirely with a cloud version [4] is much more broad, involved, and risky, than downloading and installing a plugin. 

Downloading and installing the plugin might work, but probably not due to aforementioned customized, modified TinyMCE. [5] I did find mention of an "API Key" implying that A11ychecker could simply be a working plugin that makes API calls, but that would mean we fall into Cloud Pricing, not any more affordable than server pricing. I could not research more without starting a "free trial."

Side note: A11ychecker documentation has some pretty unique strings, ie. primary keys, and I found "a11ycheck" in WordPress' code [6] I researched if, somehow, it was possible to turn this on. I could not figure it out. On the same line of code are "spellchecker" and "spellcheckerlanguage", strings that describe features which we looked at before and could not get working, which makes me think this is either leftover junk from WordPress' customized TinyMCE, or it's WordPress dot com related.

Executive summary: 
+ A11ychecker is an estimated $400 a month, maybe less, probably more.
+ We should determine if our customers are be willing to pay before exploring this plugin any further
+ Getting it working will take developer time, with a strong chance of it breaking our stuff.

[1] https://www.tiny.cloud/docs/plugins/a11ychecker/
[2] https://www.tiny.cloud/pricing/
[3] https://github.com/pressbooks/pressbooks/blob/dev/inc/editor/namespace.php
[4] https://go.tiny.cloud/wordpress/
[5] https://www.tiny.cloud/docs/integrations/wordpress/
[6] https://github.com/WordPress/wordpress-develop/blob/84f073cc52ffe298169ab659286daed5efe26b26/src/js/_enqueues/vendor/tinymce/themes/modern/theme.js#L799

**Comment by connerbw** [comment]
**instructure/tinymce-a11y-checker:**

Install npm modules:

`npm install tinymce-a11y-checker --save`
`npm install @instructure/ui-themes --save`

Create a `tinymce-a11y-checker.js.` file that contains:

```js
import 'tinymce-a11y-checker'
import { canvas } from '@instructure/ui-themes'
canvas.use();
```

Use our webpack.mix tools to compile it:

```js
.js( 'assets/src/scripts/tinymce-a11y-checker.js', 'assets/dist/scripts/tinymce-a11y-checker.js' )
```

Edit `pressbooks/inc/editor/namespace.php` and load the compiled file, activate the button, in TinyMCE.

```
// \Pressbooks\Editor\mce_buttons_3 
array_push( $buttons, 'apply_class', 'anchor', 'superscript', 'subscript', 'wp_code', 'check_a11y' );

// \Pressbooks\Editor\mce_button_scripts
$plugin_array['a11y_checker'] = $assets->getPath( 'scripts/tinymce-a11y-checker.js' );
```

Wedged in, more or less works:

![Wedged-In-1](https://user-images.githubusercontent.com/812192/64879310-b297c100-d623-11e9-9366-739a846efc97.png)

![Wedged-In-2](https://user-images.githubusercontent.com/812192/64879312-b297c100-d623-11e9-855f-575bbe08c343.png)

Would require development time to make it look not gross.  It's in React [1] [2], not CSS.  Would require a good amount of testing to make sure slapping React on top of our WordPress editor doesn't break the GUI.

[1] https://instructure.design/
[2] https://github.com/instructure/tinymce-a11y-checker/issues/52

**Comment by connerbw** [comment]
> 4. Would you recommend implementing one over the other, or choosing neither (with brief justification)?

We should chose instructure/tinymce-a11y-checker because it is open source.

> 3. If implemented, what drawbacks/unintended consequences do you foresee?

High learning curve to improve it, contribute back upstream.

> 2. If so, can we provide a rough effort estimation for doing so?

No. :) At least one sprint. Let's discuss in planning.
