### ISSUE TITLE
Improve speed/performance of the v2 API for books

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1796]

**Comment by connerbw** [comment]
https://github.com/pressbooks/pressbooks/pull/1805
https://github.com/pressbooks/pressbooks-aldine/pull/192

**Comment by connerbw** [comment]
# Pressbooks

+ Remove `/wp-json/pressbooks/v2/books/search`
+ Remove` /wp-json/pressbooks/v2/books` fulltext search

This is not good enough. We need to rethink how to do this. Possible hint: WP_Site_Query, WP_Network_Query, "Now after the filter `networks_pre_query` and `sites_pre_query run`, the code will exit straight away. This allows developers to completely hot-wire the network and site query, to load from another source, such as a different cache or Elastic search." 

Source: https://make.wordpress.org/core/2019/10/15/enhancements-to-the-network-sites-screen-in-wordpress-5-3/

+ Simplify and speed up the output of `/pressbooks/v2/books`
+ Remove pb-api (Api_v1) - TODO: https://github.com/pressbooks/pb-api/issues/3
+ Fix: wp_blogmeta copy was stale, off-by-1-clear-cache
+ Store all book info as array and JSON
+ Add get() with auto-sync

Note: Instead of makling a `/v3` We're making the assumption that no one uses `/pressbooks/v2/books` and being bad open source citizens by removing the Network API `toc` node (because we don't want people using it). The `toc` node still exists in each Book API. We will be adding more schema,org compatible info into the metadata node in the upcoming weeks.

# Aldine

Use wp_blogmeta to speed up catalog
Fixes TODO in reference to:  https://core.trac.wordpress.org/ticket/37923
Depends on https://github.com/pressbooks/pressbooks/pull/1805
