### ISSUE TITLE
Identify root cause of cloning outage problem & recommend solution

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1916]
Some cloning operations are causing database bottlenecks and taking down servers. Find and fix problem in cloning routine.

This book (cloned from eCampusOntario's network): https://integrations.pressbooks.network/clonetextproblem/ previously caused network outages when we tried to do an intra network clone. Our suspicion was that it may be because it has nearly 3000 glossary terms (took over 10 minutes to clone).

**Comment by SteelWagstaff** [comment]
@cagp-dev-mtl recommended http://kcachegrind.sourceforge.net/html/Home.html. Once @ho-man-chan has working Xdebug with breakpoints and working manual install Kachgrind, he can schedule short intro meeting with Carlos

**Comment by ricardopressbooks** [comment]
In order to understand the clonning process flow at the code level:
1. The book source is readed through API: Front matters, Back matters, Glossaries, Parts, Chapters and every metadata [is readed from source API](https://github.com/pressbooks/pressbooks/blob/9aaea5e1c7ececf2e44bd3968e8e3fc05e13b642/inc/cloner/class-cloner.php#L859). Also the [structure](https://github.com/pressbooks/pressbooks/blob/9aaea5e1c7ececf2e44bd3968e8e3fc05e13b642/inc/cloner/class-cloner.php#L828).
2. For each element readed, it is stored in [big array variables](https://github.com/pressbooks/pressbooks/blob/9aaea5e1c7ececf2e44bd3968e8e3fc05e13b642/inc/cloner/class-cloner.php#L534).
3. [Each variable (array) is iterated](https://github.com/pressbooks/pressbooks/blob/9aaea5e1c7ececf2e44bd3968e8e3fc05e13b642/inc/cloner/class-cloner.php#L422) and for each one of the element, [it's stored using POST method to the API](https://github.com/pressbooks/pressbooks/blob/9aaea5e1c7ececf2e44bd3968e8e3fc05e13b642/inc/cloner/class-cloner.php#L1431) in the end side.

### Problems & proposed solutions
Read process is quite performant. **The most bigger bottleneck seems to be in the writting process** (send a POST for each element for each taxonomy). This causes a huge amount of queries in the database.
Improvement to the DB level is not an option, since Wordpress DB structure require a way to store different resources in a specific way.
We could try some improvements to code level:
- There are some unnecessary loops/iterations we could avoid making changes in variables structure and functions. It should improve a little bit our [CPU and RAM usage](https://docs.google.com/document/d/1qddTBapryBFpNaTU5dKhFkFdCX9X9tLENLxX43ZtdEw/edit)
- Destroy/Delete arrays after an insert ([it should also improve the CPU and RAM usage](https://docs.google.com/document/d/1qddTBapryBFpNaTU5dKhFkFdCX9X9tLENLxX43ZtdEw/edit))
- Create new API POST endpoints (or make changes in the current ones) to accept multiple inserts in single calls (bulk). It should improve significantly the DB usage, since we would be doing massive inserts in a few queries.

The suggested estimate for those changes is XL, since we will need:
- Understand the complete code and process to make changes in the correct places
- Apply changes
- Test manually with different books and environments
- Create new unit tests
