### ISSUE TITLE
Uncaught error related to Lord of the Files 

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#1981]
Since LOTF 1.0 release, we've been unable to deploy to production because of a memory leak upon deploy. 

Dac built a file checking solution that makes use of Lord of the Files, though I don't understand it very well. See https://github.com/pressbooks/pressbooks/blob/23a0975512162c53daf17d3d70a149a5038ea8ad/inc/media/namespace.php#L65-L119

See also https://github.com/pressbooks/pressbooks/pull/1817 + https://github.com/pressbooks/pressbooks/issues/1803 for more context. 
 
Additional information:
The aliases file referenced in https://github.com/pressbooks/pressbooks/blob/98bbf01aea32a8695f2d19ee34c4dcbbe6e4390d/inc/media/namespace.php#L103 is in a repo that's no longer maintained: https://github.com/Blobfolio/blob-mimes/blob/master/wp/lib/blobfolio/wp/bm/mime/aliases.php (retired in favor of https://github.com/Blobfolio/righteous-mimes)

Several filters have been deprecated since 1.0, including blobmimes_get_mime_aliases (which we hook into: https://github.com/pressbooks/pressbooks/search?q=blobmimes&unscoped_q=blobmimes)
![Screenshot from 2020-07-15 21-01-43](https://user-images.githubusercontent.com/13485451/87618470-8df6f480-c6df-11ea-883c-be8f058a9558.png)

When I attempt to visit file settings on my local environment, I see a Fatal error: Uncaught Error: Maximum function nesting level of '200' reached, aborting! in /srv/www/pressbooks.test/current/web/wp/wp-includes/user.php on line 440. The repeated loop appears to be 

get_allowed_mime_types( )	.../settings.php:52
apply_filters( )	.../functions.php:3190
WP_Hook->apply_filters( )	.../plugin.php:206
Pressbooks\Media\add_lord_of_the_files_types( )	.../class-wp-hook.php:289
blobfolio\wp\bm\mime::get_aliases( )	.../namespace.php:82
blobfolio\wp\bm\mime::_wp_mimes( )	.../mime.php:77

![screencapture-pressbooks-test-testbook-wp-admin-options-general-php-2020-07-15-21_00_43](https://user-images.githubusercontent.com/13485451/87619055-e7abee80-c6e0-11ea-9a27-7c0b226be399.png

I also see an Notice for an undefined variable when I attempt to visit the file settings menu when the plugin is not network enabled by turned on in an individual book:
![Screenshot from 2020-07-15 21-23-17](https://user-images.githubusercontent.com/13485451/87619294-89334000-c6e1-11ea-9644-3962c84b389e.png)

**Comment by joshstoik1** [comment]
The `blobfolio\wp\bm\mime::get_aliases()` method called by `add_lord_of_the_files_types()` factors local (site/user) aliases into its response, which it collects with calls to `get_allowed_mime_types()` and/or `wp_get_mime_types()` (which in turn apply the `upload_mimes` or `mime_types` filters respectively).

If `add_lord_of_the_files_types()` is hooked into either `upload_mimes` or `mime_types`, that'd be the origin of the loop.

Here are the relevant LotF methods:
```php
/**
 * Return MIME aliases for a particular file extension.
 *
 * @param string $ext File extension.
 * @return array|bool MIME types or false.
 */
public static function get_aliases(string $ext='') {
	// If the extension is totally bogus there's nothing for us to even filter.
	if (! $ext || (null === $ext = self::_sanitize_ext($ext))) {
		return false;
	}

	$out = array();

	// Add our known aliases.
	if (isset(aliases::TYPES[$ext])) {
		$out = aliases::TYPES[$ext];

		// Add group data?
		if (
			'gz' !== $ext &&
			'zip' !== $ext &&
			isset(aliases::GROUPS[$ext])
		) {
			if (aliases::GROUP_GZIP & aliases::GROUPS[$ext]) {
				$out = \array_merge($out, aliases::TYPES['gz']);
			}
			if (aliases::GROUP_JSON & aliases::GROUPS[$ext]) {
				$out = \array_merge($out, aliases::TYPES['json']);
			}
			if (aliases::GROUP_TEXT & aliases::GROUPS[$ext]) {
				$out[] = 'text/plain';
			}
			if (aliases::GROUP_XML & aliases::GROUPS[$ext]) {
				$out[] = 'application/xml';
				$out[] = 'text/xml';
			}
			if (aliases::GROUP_ZIP & aliases::GROUPS[$ext]) {
				$out[] = 'application/zip';
				$out[] = 'application/octet-stream';
			}
		}
	}

	// WP's information *should* already be in our list but people do weird things sometimes...
	if (null !== $type = self::_wp_mimes($ext)) {
		$out[] = $type;
	}

	if (empty($out)) {
		$out = false;
	}
	else {
		$out = \array_unique($out);
		\sort($out);
	}

	// Filter.
	return admin::filter('lotf_get_mime_aliases', array($out, $ext));
}

/**
 * Mapped WP MIME Types
 *
 * Return allowed MIMEs mapped for searching by extension.
 *
 * @param ?string $ext Extension.
 * @param bool $strict Only allowed types.
 * @return mixed Type(s) or null.
 */
private static function _wp_mimes(?string $ext = null, bool $strict = false) {
	$search = null;
	if ($ext && (null === $search = self::_sanitize_ext($ext))) {
		return null;
	}

	$out = array();

	// Lord of the Files factors WordPress' default types into its static list so we can ignore it unless a site hooks into the "mime_types" filter.
	if (! $strict && \has_filter('mime_types')) {
		$tmp = \wp_get_mime_types();
		if (! empty($tmp)) {
			foreach ($tmp as $exts=>$type) {
				if (null === $type = self::_sanitize_type($type)) {
					continue;
				}

				// Just one extension.
				if (false === \strpos($exts, '|')) {
					if (null !== ($exts = self::_sanitize_ext($exts))) {
						$out[$exts] = $type;
					}
				}
				// Multiple extensions.
				else {
					$exts = \explode('|', $exts);
					foreach ($exts as $ext) {
						if (null !== $ext = self::_sanitize_ext($ext)) {
							$out[$ext] = $type;
						}
					}
				}
			}
		}
	}

	// We should always pull the allowed types explicitly.
	$tmp = \get_allowed_mime_types();
	if (! empty($tmp)) {
		foreach ($tmp as $exts=>$type) {
			if (null === $type = self::_sanitize_type($type)) {
				continue;
			}

			// Just one extension.
			if (false === \strpos($exts, '|')) {
				if (null !== ($exts = self::_sanitize_ext($exts))) {
					$out[$exts] = $type;
				}
			}
			// Multiple extensions.
			else {
				$exts = \explode('|', $exts);
				foreach ($exts as $ext) {
					if (null !== $ext = self::_sanitize_ext($ext)) {
						$out[$ext] = $type;
					}
				}
			}
		}
	}

	// Do we just want a specific entry?
	if ($search) {
		return $out[$search] ?? null;
	}

	// Sort and return them all.
	\ksort($out);
	return $out;
}
```

One other issue I see with `add_lord_of_the_files_types()` I see is:
```php
if ( $extra_mime_alias ) { 
	$upload_filetype_mimes[ $k ] = $extra_mime_alias[0]; // The first MIME entry is the official (or most conventional) media type 
}
```

The LotF plugin does not rank MIME aliases by officialness; they're just sorted alphabetically for matching purposes.

In any context where a singular value is expected, LotF ultimately defers to the given WordPress instance for its favored type definition (or `false` if WP doesn't allow it), keeping it consistent with WP's naive methods like `wp_check_filetype`. (This also ensures consistent database storage, which can be important sometimes.)

The road to parity is a little more complicated during file upload validation, but basically what ends up happening is if LotF discovers "foobar.jpg" is actually a PNG, it will rename it `foobar.png`, then return the type the WP instance associates with PNG files.

> I also see an Notice for an undefined variable when I attempt to visit the file settings menu when the plugin is not network enabled by turned on in an individual book

Ah, thank you! That Notice doesn't really break anything, but will be fixed in the next release!

**Comment by joshstoik1** [comment]
Building off the last response, I believe the loop can be avoided by rewriting `add_lord_of_the_files_types` like:

```php
function add_lord_of_the_files_types( $existing_mimes = [] ) {
	$upload_filetype_mimes = [];
	$lord_of_the_files_activated = ( is_plugin_active_for_network( 'blob-mimes/index.php' ) || is_plugin_active( 'blob-mimes/h5p.php' ) ) && class_exists( 'blobfolio\\wp\\bm\\mime\\aliases' );
	if ( $lord_of_the_files_activated ) {
		foreach ( unknown_upload_types( $existing_mimes ) as $k => $v ) {
			$v = strtolower( sanitize_mime_type( $v ) );
			if ( $v && isset( \blobfolio\wp\bm\mime\aliases::TYPES[$k] ) ) {
				$upload_filetype_mimes[ $k ] = $v;
			}
		}
	}
	if ( ! empty( $upload_filetype_mimes ) ) {
		$existing_mimes = array_merge( $upload_filetype_mimes, $existing_mimes );
	}

	return $existing_mimes;
}
```

The question of whether or not LotF has an entry for a given extension can be answered directly by checking the `\blobfolio\wp\bm\mime\aliases::TYPES` constant (no filters, etc.).

The type to add should really just be a (sanitized) version of the user's value `$v`, since that is what native WP methods would be expecting, and what LotF will defer to in cases where everything else checks out.

Type authority is in a weird state at the moment, similar to "reality" in "politics".

LotF errs with the side of self-consistency, assuming it is more important that a given WP instance be consistent with itself rather than having some methods report one value and others a different value.

If you wanted to lean more toward Official (i.e. not trusting the user's `$v`), the Righteous MIMEs PHP library does attempt to [sort extension/type pairings by authority](https://github.com/Blobfolio/righteous-mimes/blob/master/lib/righteous/mimes/data/extensions.php#L66) (a sort of weighted consensus). It isn't _perfect_ — authorities often disagree with one another, have different scopes, and sometimes prefer backward compatibility to temporal accuracy — but it is somewhere between _good_ and _very good_, certainly the best single reference there is at the moment. :wink: 

(That same data is available in [JSON format](https://github.com/Blobfolio/righteous-mimes/blob/master/bin/extensions.json), so can be referenced without the full library (which you probably don't need), or even without PHP.)

**Comment by cagp-dev-mtl** [comment]
Fixed with PR #1995

**Comment by cagp-dev-mtl** [comment]
After debugging on staging, there are two changes that fix the issue:

1) Update hook name: 
-add_filter( 'blobmimes_get_mime_aliases', '\Pressbooks\Media\get_lord_of_the_files_mime_aliases', 10, 2 );
+add_filter( 'lotf_get_mime_aliases', '\Pressbooks\Media\get_lord_of_the_files_mime_aliases', 10, 2 );

By disabling plugin `wpackagist-plugin/enable-media-replace` I was able to find the source of the infinite loop that causes the memory leak. After finding the source of the issue I restored this plugin, therefore, there is no need to modify `enable-media-replace` in the bedrocks.

2) Disabled the hook below, which became redundant after the latest release of LOTF.
`add_filter( 'upload_mimes', '\Pressbooks\Media\add_lord_of_the_files_types', 11 );` which added extra media types.

@SteelWagstaff , @ho-man-chan , since you have experience using this plugin, can you pls test the new version 1.1.5 on integrations. 

If this fix maintains the plugin functionality, I will remove the un-used methods/tests that resulted by disabling our custom types registration hook.

**Comment by joshstoik1** [comment]
@SteelWagstaff I went ahead and released LOTF 1.1.6 a couple days early in case you wanted to test against that version too. It's just a routine release, but includes the extra MuseScore format handling you had asked me about earlier.

**Comment by SteelWagstaff** [comment]
@cagp-dev-mtl I think the removal of the `add_filter ('upload_mimes' ...` is resulting in the loss of expected functionality. 

For example, Dac writes: "If "Lord of the files" is installed, and the Network Administrator wants to allow extra file extensions under Network Settings, and we can guess the mime type, then Upload File Types should work now."
> https://github.com/pressbooks/pressbooks/issues/1803#issuecomment-548043294

I've added mscx as an allowed file type under network settings
![mscx_allowed_upload_file_type](https://user-images.githubusercontent.com/13485451/88846617-7a519080-d1ab-11ea-9d12-c5aa096cda7e.png)

And confirmed through file validation that the file tested (which I grabbed from this public repo which includes MuseScore examples) matches the expected file type
![Debug_validation](https://user-images.githubusercontent.com/13485451/88846664-8c333380-d1ab-11ea-8bb7-7b589cb32f3c.png)

However, when I attempt to upload the file into the media library, I see a 'this file type not permitted for security reasons' error message. I believe that this is what the add_filter line allowed us to work around previously.

**Comment by joshstoik1** [comment]
Yeah, if the original method was _augmenting_ the allowed types list, removing its hook will just cause those types not to be added.

My quickie example [a few replies up](https://github.com/pressbooks/pressbooks/issues/1981#issuecomment-660538820) showed a potential workaround inside that method, having it run its checks against static data instead of calling methods (which trigger the same filter this method is hooked to, hence the loop...). That should be enough to let it do its thing, and LOTF do its thing, without the two warping space and time in the process. Haha.

That example is untested and may contain typos, but the main idea is that LOTF organizes its internal data into a static constant keyed by extension. Something like `isset( \blobfolio\wp\bm\mime\aliases::TYPES[$k] )` would answer the question, "Is this extension known?". (Though since literals are being matched, it might be worth adding a line beforehand to force `$k` to lowercase and strip any periods just in case the user data is not formatted quite right.)

**Comment by cagp-dev-mtl** [comment]
Restored file types hook and implemented @joshstoik1 solution with a slight variation on #1999 

Thanks, @joshstoik1 :raised_hands:

**Comment by SteelWagstaff** [comment]
Tested on integrations -- was able to successfully register new file type and add and upload mscx files to sample book. Looks good to me. Thanks @cagp-dev-mtl & @joshstoik1!
