### ISSUE TITLE
Update Thema to latest version

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2105]
Pressbooks ships with an open source subject taxonomy called [Thema](https://www.editeur.org/151/Thema) (by EDitEUR). We updated to v1.3 in 2018 (https://github.com/pressbooks/pressbooks/pull/1266/). The current version is 1.4.2 (released in October 2020).  More details below:
> Thema version 1.4 was released at the beginning of April 2020. This version contains 143 new core subject categories and 549 new qualifiers (including new national extensions), plus numerous improvements to the wording of headings and notes, but it retains full backward compatibility with version 1.3 (no existing data needs to be modified or updated). 
> Version 1.4.2 was released in October 2020 with 40 new national qualifiers added. This remains fully backward compatable and all the new national qualifers can be taken back to their root codes for those implementors who do not need to use the national qualifiers.

Many more details and resources about Thema available at https://www.editeur.org/151/Thema

To update from 1.3 to 1.4.2 we would need to update the files available in the Thema symbionts folder: https://github.com/pressbooks/pressbooks/tree/dev/symbionts/thema. See https://github.com/pressbooks/pressbooks/pull/1266/files for the PR which updated to use Thema 1.3.

- [x] Create public repo to host all json files
- [x] Create logic to check for four character language strings (i.e. fr-ca)
- [x] Create routine to fetch json files for requested languages

**Comment by SteelWagstaff** [comment]
Branch with changes in progress at https://github.com/pressbooks/pressbooks/tree/pb-2015-thema-update

**Comment by SteelWagstaff** [comment]
Thoughts from Ned
> I took a look at the code and I think this is the relevant part: https://github.com/pressbooks/pressbooks/blob/0e8c4f5f4f49c501e0ba2b29ff2662751e5bba07/inc/metadata/namespace.php#L884.

> Specifically, the way that Thema subjects are currently retrieved in the appropriate language uses a two-letter locale (en, fr, or es, for example). The locale is set based on the first two characters of the book locale, which for Kindle reasons has to be one of the languages in that supported_languages() array (supposedly, although it is probably worth checking that assumption since according to the function comment it relies on [an 11-year-old forum post](https://www.mobileread.com/forums/showpost.php?p=2453537&postcount=2)). Since the Thema subjects have regional language variants now (for example, fr-ca), that complicates matters and would necessitate some logic to check for longer book locales which have a corresponding Thema translation and apply the corresponding Thema translation. Here's a rough attempt at what that might look like: https://gist.github.com/greatislander/4029893934846c4a942278c81d645121

1. Check to see if the full book locale matches.
2. If it doesn't, check to see if the truncated, two-character version of the book locale matches.
3. If it doesn't, fall back to `en`.

> As for the file size question, I would suggest that the same approach be taken as was taken with global fonts — download them on demand if a user's book language is set to one of the more uncommon languages. Here's where that happens in global typography. https://github.com/pressbooks/pressbooks/blob/555024f17a1b9d818e316f17c20fcb9495730dd4/inc/class-globaltypography.php#L419-L462

**Comment by SteelWagstaff** [comment]
See https://www.bookbusinessmag.com/article/why-us-publishing-industry-should-care-thema-global-standards/ + https://bisg.org/news/461958/Thema-in-a-Global-Marketplace.htm

**Comment by richard015ar** [comment]
## Manual test results
Test cases tested, with a book on Integrations with different thema subjects applied:
- I selected different languages available for Thema and it works as expected, the subject language changes with the language selected. I used languages with existing translation like French and Japenese (this is a new one for the new Thema version).
- I also selected languages unsupported by new Thema version and the English version of the subjects are displayed as expected in those cases. I used Zulu and Urdu languages.
- I was not able to test compatibility issues, since I didn't find any book in Integrations with language/subject combination for the previous Thema version. But I tested locally in the following way:
  - I checkout to the previous version of the repo and stored a subject in Japanese (unsupported by previous version of Thema). And then I moved to this branch and the subject was transalated _using the new Thema subjects as expected._
