### ISSUE TITLE
Export Validation Error emails do not get sent

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks#2144]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Found through this client interaction: https://pressbooks.zendesk.com/agent/filters/360147261192

Export Validation Logs can be turned on in any book through **Settings**>**Exports**>**Email Validation Logs**. 

With this setting turned on, if/when there is a validation error on the formats which are being exported, the user who is exporting will receive the error logs to their email inbox. 
<img width="1201" alt="Screen Shot 2021-04-22 at 1 25 50 PM" src="https://user-images.githubusercontent.com/61845107/115759470-44be8a00-a36e-11eb-935c-fb71cf86e1ad.png">

These error logs help the user by helping them locate where the issue is, so that the user can 'de-bug'/fix their file.

Bug: these emails are not being received at the email stated.

### Steps to Reproduce

1. Find a book that is producing validation errors (here's an example: https://university.pressbooks.pub/exportvalidation)
2. Make sure that Email Validation Logs are turned on at: **Settings** > **Export** > **Email Validation Logs**
3. Create exports and wait to see if email shows up in inbox.
 
**Expected behavior:** Email should be sent to inbox containing validation errors.

**Actual behavior:** Message shows on the top of the Exports page indicating validation errors, but no emails are sent.

**Comment by SteelWagstaff** [comment]
We can potentially fix this by adding a better check to https://github.com/pressbooks/pressbooks/blob/d877d5012da2c889afb087f682c27c5e565f0c43/inc/utility/namespace.php#L876-L886. We could use the network admin email as the first else statement if no WP_MAIL_FROM value is found.

**Comment by SteelWagstaff** [comment]
This issue ended up being related to the client's DMARC configuaration rather than a Pressbooks bug. We use a service called Mailgun to send confirmation emails, password resets, and error logs for Pressbooks networks. Pressbooks staff can check for outgoing errors in our [Mailgun dashboard](https://app.mailgun.com/app/sending/domains/mg.pressbooks.pub/logs)

On some networks, we will occasionally see an error message like the following: "5.7.26 Unauthenticated email from [USERDOMAIN] is not accepted due to domain's DMARC policy. Please contact the administrator of [USERDOMAIN] domain. Please visit https://support.google.com/mail/answer/2451690 to learn about the DMARC initiative." 

We've had a small number of clients who had this problem in the past, and they fixed this issue by changing their DMARC policy, presumably based on what was in the support link.
