### ISSUE TITLE
[Research] Refactor ODT and DOCX exports using PHPWord

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2187]
Our current export routine for ODT files takes the books XHTML files and transforms it using an XSL stylesheet (https://github.com/pressbooks/pressbooks/blob/dev/inc/modules/export/odt/xhtml2odt.xsl). 
See https://github.com/pressbooks/pressbooks/blob/86d59a1daf6b2c8f2c9977faf045a9e043549587/inc/modules/export/odt/class-odt.php#L93

Our current import routine for ODF and DOC (OOXML) files also use XSL to parse and convert the files for use in Pressbooks. See https://github.com/pressbooks/pressbooks/blob/dev/inc/modules/import/odf/class-odt.php + https://github.com/pressbooks/pressbooks/blob/dev/inc/modules/import/ooxml/class-docx.php

Each of these processes are brittle and hard for us to maintain/improve. Ned/Dac recommended refactoring existing ODT and DOCX export routines using this well-established library: https://github.com/PHPOffice/PHPWord. Documentation at https://phpword.readthedocs.io/en/latest/

As a part of this research task, I'd like a developer on our team to familiarize themselves with our export/import routines and with this PHPWord library in order to assess whether using this library could improve our existing document export/import routines. Done means that they have written a brief description of their findings along with a set of recommendations for improving our existing routines (ideally with GitHub issues that could be discussed in a future backlog refinement meeting). A proof of concept or sample demo implementation using Pressbooks XHTML and this library would be welcomed.

**Comment by arzola** [comment]
# PHPOffice
After an extensive Research in our current ODT/OOXML implementation it seems there are some room for improvement to standardize the Word / OpenDocument format generation.

## Current state
We have implemented the ODT (Open Document) format, the Microsoft Word format is not supported for exports.

We use a single XSL stylesheet to transform and map the Pressbooks XHTML into an ODT XML file, this XSL is too big to maintain and update due the complexity of the transformations, if we decide to continue using XSL stylesheets I suggest to divide them into more manageable parts like this: [xhtml2odt/xsl at master · abompard/xhtml2odt · GitHub](https://github.com/abompard/xhtml2odt/tree/master/xsl)

### Main Issues

1. ODT exports are currently broken and it’s producing corrupted files (My suspicion is the new contributors structure and the changes in the markup with the new features added, or maybe has been broken)
2. Current XSL transformation is kind of dark and unknown, we probably need to have a better MAP structure as I suggested before.

## Is it possible to implement PHPWord to produce valid, clean and maintainable ODT/Word files?
> Short answer: yes

But.

### It would require some work

1. We would need to create the general document schema using PHPWord to create the right XML body with the right schema definitions and also being able to customize ODT/OOXML metadata in a standardized way.
2. Review if it’s useful to have some XSL stylesheets to transform the content and append those transformations in PHPWord because PHPWord has XSL support.
	* If XSL is not an option we could reuse the exportHelpers trait to generate the content and pass it to PHPWord using the `section::addHtml` method.
3. We would need to fix/replace images to embed the images inside the document (similar for PDF)
4. We would need to map some methods to create the TOC, footnotes and endnotes and review embed objects rendering.


## Proof of concept result
1. Library installation with a composer require command, no external libraries needed just the simple XML manipulation libraries (already installed)
2. I was able to generate an ODT and a OOXML (Word) file with a new Pressbooks book using the HTML but some local images are broken (external works good) I think is something related to the self signed certificate and it was not able to download the images from pressbooks.test.
3. The TOC has the links in place
4. Everything was printed in the same page (due inexistent XSL transformation) so the page breaks doesn’t exists.

**Comment by SteelWagstaff** [comment]
**Questions:** 
1. Will you create a branch with this PoC so we can test this on the experimental branch? I'd like to see what happens with images there
2. I didn't see anything in the report about the document import routine. What were your findings there?

**Comment by arzola** [comment]
I updated the comment, tomorrow we can discuss about this 🤓 and I sent a little PoC using the library.
