### ISSUE TITLE
[Research] Improve EPUB export routine

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2194]
### Feature Description

At present, Pressbooks allows users to produce EPUB exports in two formats: 2.01 and 3. EPUB 2 is still the default 'supported' format, and EPUB 3 is listed as an 'Other format'. 

![Screenshot from 2021-07-29 08-33-23.png](https://images.zenhubusercontent.com/6012398f80b7cb0f8d1385bc/e201427a-0312-4022-bfab-16d9ed0c0a92)

The EPUB 2 spec was approved in 2007, with [2.01](https://en.wikipedia.org/wiki/EPUB#Version_2.0.1) approved in September 2010. The EPUB 3 spec was approved in October 2011 (see [changes](http://idpf.org/epub/30/spec/epub30-changes.html)), with [3.0.1] approved as a minor maintenance update in June 2014. The [final specification for EPUB 3.2](https://www.w3.org/publishing/epub3/epub-spec.html), which superceds EPUB 3.01 was released by a W3C community group in 2019. See https://www.w3.org/blog/2018/04/why-specs-change-epub-3-2-and-the-evolution-of-the-ebook-ecosystem/ for a good overview of EPUB specifications in the 3 family and how they are related.

We should update Pressbooks' export routine (see https://github.com/pressbooks/pressbooks/tree/dev/inc/modules/export/epub) so that it produces well-formatted EPUB 3.2 files and consider retiring other EPUB export versions. This will require refactoring our EPUB export routines, since our EPUB 3 routine currently extends the EPUB 2.0.1 class: https://github.com/pressbooks/pressbooks/blob/5ff190b0c04833eb8cf4434cc1d38414d654a3d6/inc/modules/export/epub/class-epub3.php#L17. We should also ensure that our EPUB files comply with Amazon's [KDP guidelines](https://kdp.amazon.com/en_US/help/topic/GU72M65VRFPH43L6) and other similar guidelines for online book sellers to the greatest degree possible, since many Pressbooks authors intend to publish their books with Amazon and other online services.

We may also want to update the version of EPUB check we recommend as a dependency with Pressbooks. Our servers currently use version [4.1.1](https://github.com/pressbooks/sample-infrastructure/commit/d74ff48b7cf493795d4b9c5e6110803570ca427a) but [latest release](https://github.com/w3c/epubcheck/releases/) is now 4.2.6.

## Notes

The DAISY Consortium provides a few helpful validation and a11y tools for EPUBs, including [EPUB Check](https://github.com/w3c/epubcheck) [which is installed as a necessary sever dependency and used by Pressbooks as part of our EPUB export routine] and [Ace](https://inclusivepublishing.org/toolbox/accessibility-checker/getting-started/), which can be used as a command-line tool or a [desktop application](https://inclusivepublishing.org/toolbox/ace-by-daisy-app/)

**Comment by SteelWagstaff** [comment]
See also: https://github.com/pressbooks/pressbooks/issues/1859#issuecomment-559169492

**Comment by richard015ar** [comment]
## Research notes
We are using EPUB 3.0.1 for exporting, so in general terms we need to:
- Create a single `Epub` class instead una for EPUB 2 and other for EPUB 3, since we will deprecate EPUB v2 and other EPUB v3, exporting only 3.2 version.
- Fix some of the HTML and CSS issues mentioned in https://github.com/pressbooks/pressbooks/issues/2194#issuecomment-846436538. Some of those issues could be avoided since these were deprecated for EPUB 3.2.
- Adapt the `Epub` class to upgrade the current EPUB 3.0.1 to EPUB 3.2 version. For these, we need to consider some of the [changes released](https://www.w3.org/publishing/epub3/epub-changes.html) respect from v3.0.1.

### Upgrading 3.0.1 to 3.2
Reviewing the changes made in EPUB 3.2 revision specifications, these are the most important considerations we would like to work:

#### Accessibility
The EPUB 3.2 revision introduces the [EPUBAccessibility](http://idpf.org/epub/a11y/accessibility.html.) specification, which details how to make EPUB Publications accessible and discoverable. This specification leverages the work of [WCAG20](https://www.w3.org/TR/WCAG20/) and also adds requirements for EPUB Publications. It is accompanied by the informative [EPUBAccessibilityTechniques](http://idpf.org/epub/a11y/techniques/techniques.html) document that describes best practices for meeting the requirements. This specification is designed to be applicable to older versions of EPUB. It can be used immediately by Authors to check whether their EPUB 3.0.1 or 2.0.1 Publications are accessible.
See the notes section in this ticket for tools that could be helpful  for this.

#### Considering the biggest change is in the relationship to the core web specs of HTML, CSS and SVG as defined by W3C, but also others new features were added and others were deprecated:
- EPUB 3.2 adds the WOFF 2.0 and SFNT font formats as Core Media Type Resources
- There are metadata changes to consider: https://www.w3.org/publishing/epub3/epub-changes.html#sec-pkg-metadata-changes
- EPUB 3.2 adds an additional clarification that foreign resources do not require fallbacks if they are not in the spine and not embedded in EPUB Content Documents. This change will allow authors to include data files for use by scripts without unnecessary fallbacks, among other benefits: https://www.w3.org/publishing/epub3/epub-spec.html#sec-resource-locations (audio, etc)
- There are changes the precedence order of linked records, prioritizing bibliographic information in linked records over the information included directly in the Package Document metadata element.
- This version also removes the EPUB Style Sheets profile. In its place, more general CSS support requirements are being defined: https://www.w3.org/publishing/epub3/epub-changes.html#sec-cdoc-css
- A guidance was added that Reading Systems should prioritize the style choices of Authors and users over its own user agent styles through the addition of Reading System conformance requirements and a subsection on overriding styles.
- Unprefixed values that are not part of the EPUB Structural Semantics Vocabulary [EPUB-SSV] are allowed to be used in the epub:type attribute. Consider it in the fixes required in https://github.com/pressbooks/pressbooks/issues/2194#issuecomment-846436538.
-  EPUB 3.2 makes changes to scripting support: https://www.w3.org/publishing/epub3/epub-changes.html#sec-cdoc-scripting: The order of encryption and compression has been clarified. The new rules clarify that compression is not necessary when it is not beneficial to reducing the size of a resource.

### Recommendation for this task
I think we can split this big task by doing some steps, each one in different independent tasks:
- Create a single `Epub` class instead una for EPUB 2 and other for EPUB 3, since we will deprecate EPUB v2 and other EPUB v3, exporting only 3.2 version. Make sure everything works and fix / add tests. 
- Try to export to EPUB 3.2 and fix any issues required by the EpubCheck. We don't need all the new features, or fix any additional issue, just make sure the file is compatible with v3.2. Fix / add tests.
- Fix all issues mentioned in https://github.com/pressbooks/pressbooks/issues/2194#issuecomment-846436538 and any other pending issues. Add tests.
- Finally adapt and implement features in EPUB 3.2 that could be helpful and other necessary ones like accessibility, foreign resour ces embedding, etc. Create tests and make sure EpubCheck looks good. At this point we could ask a feedback from Alex Cabal if possible.
