### ISSUE TITLE
[Research] Refactor our base XHTML/HTMLBook export routines

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2210]
We currently produce XHTML exports for Pressbooks books: https://github.com/pressbooks/pressbooks/blob/dev/inc/modules/export/xhtml/class-xhtml11.php that are used as the basis for our PDF exports: https://github.com/pressbooks/pressbooks/blob/0bb89aca4f839bb790bdb9894e4c72cdb1f1ce14/inc/modules/export/prince/class-pdf.php#L83 

We should replace valid HTML5 exports instead (or in addition), and use the valid HTML5 exports as the base for extending when we produce PDF exports with Prince. Ned suggested that HTMLBook could be basis/starting point for a quality HTML5 export. We'll also want to look at our export content and make sure that it's well-formatted, semantic HTML. There are a few places where heading elements continue to be used in suboptimal ways (confusion of semantic meaning and style markup). The title page and ToC are places to look especially closely. See https://github.com/pressbooks/pressbooks/issues/1911

If/when we take this on, we'll also want to make sure that the HTMLBook routine this could be based on is updated to include any recent changes to the XHTML export routine. Like https://github.com/pressbooks/pressbooks/pull/2271 for example.

**Comment by richard015ar** [comment]
As a starting point I created a document to explain how the export routine works in our source code level: https://docs.google.com/document/d/1wED-Fm-ctORTrN0A629tLDV121weK8C6WfoBX1w8djA/edit# 

I was able to export a book to PDF using the HTMLBook instead XHTML format. Definitely it has a better HTML5 format than XHTML. Nevertheless despite we could take as a model the HTMLBook class, we should create a new class for PDF, the most challenging code to overwrite is the [transform method](https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/htmlbook/class-htmlbook.php#L185), which contains multiple HTML specifications and conditionals according to different part of the book, and make sure those are compatible with Prince.

In summary:
- Create a new class (an extension of [HTMLBook](https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/htmlbook/class-htmlbook.php#L29) is an option)
- Following the current PDF format ([see it in xhtml](https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/xhtml/class-xhtml11.php#L298)) (style, footnotes, page numbers positions, etc), create a valid well-formatted HTML5 book. This step is the most challenging part since we need to re-create the same xhtml format provided, but following the practices applied in the HTMLBook class knowing both uses different methods and ways to create the format.
- Validate the HTML5 using any tool to make sure the HTML5 is properly formatted. Test with multiple books with multiple elements.
- Replace the [url (base format)](https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/prince/class-pdf.php#L83) used in the PDF class to export the book by the new html5 format created.
- Create a new unit tests the new class.

**Comment by SteelWagstaff** [comment]
@richard015ar some remaining questions for these research tasks:
where in our XHTML/HTML output do we have improperly formatted HTML elements (for example, heading tags used incorrectly/out of order?)? For example: 
1. https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/xhtml/class-xhtml11.php#L1003-L1015
1. https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/xhtml/class-xhtml11.php#L1339-L1357
1. https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/xhtml/class-xhtml11.php#L1406-L1411
1. https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/xhtml/class-xhtml11.php#L917

etc.

Second question: where in our EPUB export routine are we also inserting poor markup. Examples: 
https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/epub/class-epub201.php#L1049-L1061 + https://github.com/pressbooks/pressbooks/blob/7ea8dd2aff224cfdf1bab8d119f1588e44772a72/inc/modules/export/epub/class-epub201.php#L1187 (heading examples)

or https://github.com/pressbooks/pressbooks/blob/3217c734b9f3d25d840c247a5ac5b16b6c1698cb/inc/modules/export/epub/templates/epub3/html.php#L25-L27 (article rather than section)

Third, if we improve the HTML/EPUB output, what will we need to change in our SCSS in Buckram/McLuhan and/or child themes to ensure that PDF exports do not break? If we make some of these elements spans, for example, we'll probably need to add display: block rules. Others may be targeting the heading element rather than the class, and we'll need to look closely at CSS rules so that title pages and other page elements don't suddenly change their appearance/function dramatically.

**Comment by richard015ar** [comment]
For point 1 and 2 we would need to check the HTML5 structure for example using: https://validator.w3.org/ for multiple books with multiple elements (multiple headers/titles/subtitles, footnotes with different elements like images, list items. The book must contains images with different alignments, text boxes, tables, etc). Once the book with different elements was exported and checked using a HTML5 checker, we would need to identify and list the specific issues and find those in our code where those element are created (all those lines should be in the classes and methods specified in the documentation created, depending on the format used).
If the issues identified are easy to change in the current class, then probably the developer won't need to re-factor too much, otherwise probably would be convenient to create a new class to create a standard well-formatted HTML5 and discard the current ones.
I left this detailed analysis to the developer who takes the feature, also I think reference lines of code (debugging process) to specific identified issues could keep the developer to solve only those, without explore and identify more using a checker/tool.
As a result of this task I considered give an idea to the developer about which classes (and its relations) they should inspect and debug, and how the main methods works (or what are the responsibilities for each one). It also, gives an insight about the approach to take the feature task (even the developer could take a better approach if he considers).

The 3rd point is pretty important for this task I think, since I did not consider the changes in SCSS, another important factor to explore and validate. Thank you for reference and clarify it.
