### ISSUE TITLE
Export and Import problem

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#222]
If i export some chapters of my book, and later i try to import, in the import área i can see the chapters i did not want to export.

![captura de pantalla 2015-08-21 a las 16 30 01](https://cloud.githubusercontent.com/assets/3929177/9410708/fa8097d8-4821-11e5-8aef-af03af2f41fe.png)

-

![captura de pantalla 2015-08-21 a las 16 30 11](https://cloud.githubusercontent.com/assets/3929177/9410713/000c87fc-4822-11e5-8daf-25f7230f11a5.png)

**Comment by greatislander** [comment]
@colomet Which export format are you using?

**Comment by colomet** [comment]
PressBooks XML

**Comment by greatislander** [comment]
My understanding is that this is the expected behaviour for Pressbooks XML exports, which are an archival format as opposed to distribution format. The use case this particular export was designed for was to migrate books between installations and  as such should include all book content—e.g. a draft chapter that is not yet ready for public consumption (thus not included in distribution exports) but still belongs in the book.

If we modify this functionality, there would need to be two options for Pressbooks XML export:

1. Archive entire book
2. Export only chapters marked for distribution export

Thoughts, @hughmcguire?

**Comment by colomet** [comment]
well, i don´t use to export in other formats, but If i can chose what to export in epub, then the sistem works almost fine. 

In my case, i use pressbooks for educational pourpouses, and i think, if we want to offer open content, we should also offer pressbooks XML to them, but sometimes we do not want to share all the chapters. Maybe because in that chapters we use some plugin shortcode and it can not be exported or because is under development, or ....

**Comment by greatislander** [comment]
Pressbooks XML is akin to the [WordPress eXtended RSS (WXR)](http://devtidbits.com/2011/03/16/the-wordpress-extended-rss-wxr-exportimport-xml-document-format-decoded-and-explained/) format and is only really useful for moving content between Pressbooks networks. If your goal is to provide open content I would suggest exporting as XHTML instead, which respects the distribution export settings on chapters, front matter and back matter. We do not currently have plans to modify the Pressbooks XML export to accommodate this use case, so I'm going to mark this issue closed.
