### ISSUE TITLE
Improve cover image prompt text & validation conditions

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2261]
- [x] Improve image upload prompt text on book info page. See https://github.com/pressbooks/pressbooks/issues/2195#issuecomment-843587220.

- [x] Enforce required size dimensions and aspect ratio upon upload. If images don't meet expected criteria, save other metadata changes and display an error message to the user letting them know their cover image wasn't uploaded and why.

**Comment by gavinpressbooks** [comment]
Tested on Integrations on https://integrations.pressbooks.network/validationtest

Works as expected. The following tests were run:
- [x] uploading a file with less than 800px of height is unsuccessful and gives "Your cover image was not saved because it is too small (516 x 750). It should be at least 800px in height."
- [x] uploading a file with less than .66 aspect ratio is unsuccessful and gives "Your cover image was not saved because the aspect ratio (1.71) is outside the permitted range (.66 to 1). We recommend an aspect ratio of .75."
- [x] uploading a file with more than 1 aspect ratio is unsuccessful and gives "Your cover image was not saved because the aspect ratio (0.56) is outside the permitted range (.66 to 1). We recommend an aspect ratio of .75."
- [x] uploading a large file (1.6 MB) with the correct aspect ratio is successful and the file is compressed down to 246 KB and 1032 by 1500 pixels.
