### ISSUE TITLE
Make compatible with latest working version of SCSSPHP

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2281]
### Description

We use a a dependency called SCSSPHP to compile SCSS into CSS in Pressbooks: https://github.com/pressbooks/pressbooks/blob/6c46984c85984ee942aa213a313d2c017f7c98ad/inc/class-sass.php#L186-L206
https://github.com/pressbooks/pressbooks/blob/6c46984c85984ee942aa213a313d2c017f7c98ad/inc/class-sass.php#L249-L275
https://github.com/pressbooks/pressbooks/blob/6c46984c85984ee942aa213a313d2c017f7c98ad/bin/compile-scss.php#L32-L40

We currently lock SCSSPHP at 1.1.1. The latest release is 1.10.0: https://github.com/scssphp/scssphp/releases. Updating to the latest breaks our tests and causes compiling errors (see https://github.com/pressbooks/pressbooks/runs/5012466833?check_suite_focus=true for example). We should fix Pressbooks so it's compatible with the latest release and bump this dependency.

**Comment by stof** [comment]
Regarding the test failure in https://github.com/pressbooks/pressbooks/runs/4736236499?check_suite_focus=true, the first one is because the default formatter changed from `nested` to `expanded` in scssphp 1.4.0 (the `nested` format has been deprecated, as it is not supported in the dart-sass reference implementation of the Sass language). This test failure is easy to fix (the only difference in your case is that the closing curly brace of the style rule goes on its own line in expanded format and on the line of the last property in nested format, even though the `nested` format also has more differences for more complex input). Note that you could even migrate to the expanded format *before* the upgrade if you want (scssphp 1.1 already supports the expanded formatter).
For the second test, I'll let someone knowning pressbooks investigate it.

Regarding the warnings during compilation, these are because styles in https://github.com/pressbooks/pressbooks-book are relying on non-standard features available in scssphp that we have deprecated. Those continue to work, but will be removed in scssphp 2.0 (that I hope to release during 2022, but without any guarantee as I'm working on scssphp on my free time). But those are only warnings, not errors, so the compilation still works like before for now.
Note also that scssphp 1.5 introduces a LoggerInterface allowing to customize where the Sass warnings are logged instead of sending them always to `php://stderr`.

Disclaimer: I'm not using pressbooks in any way. I'm one of the maintainers of scssphp and I found this repo when looking at why old versions of scssphp are still seeing significant usage in the stats. If you need help to understand how to replace deprecated features, I can answer your questions.

**Comment by SteelWagstaff** [comment]
@stof Thanks so much for this. This is one of those old dependency chores that we should tackle one of these days, but haven't gotten around to yet. This will help us when we do that -- hopefully soon!

**Comment by SteelWagstaff** [comment]
Superceded by https://github.com/pressbooks/buckram/issues/289

**Comment by SteelWagstaff** [comment]
closing in favor of https://github.com/pressbooks/private/issues/1071
