### ISSUE TITLE
allow support of arbitrary languages & fonts in any theme, through a global option theme option 

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#239]
Various Pressbooks users have need for support for various languages/fonts that aren't supported by the usual fonts we use for our themes. Over the years we've had requests for, and found ways to accommodate: Tamil, Coptic, Chinese, Biblical Hebrew, Ancient Greek, Japanese, Syrianic, Arabic (and probably more). 

We've solved this by adding these fonts to various themes, but the result is that those fonts get stuffed into the PDFs and sometimes EPUBs, regardless of whether they are needed for all books using that Theme.

So, would like to give this a more sensible approach, something like:
 
a) in book info, when user selects a language requiring a "special" font ... then a font supporting that language will load when they select any arbitrary theme.

b) on APPEARANCE >> THEMES >> THEME OPTIONS >> GLOBAL OPTIONS 
...  we add a new menu that allows users to add support for multiple languages/special fonts

c) when loading themes for export, the we pull in the CSS for font declaration, and point at the relevant font files (for EPUB, PDF, and WEB)

d)  editor.css ...also supports the selected fonts.

Bonus points for making adding a new language/font pair easy for an admin... ;-)

**Comment by jflowers45** [comment]
Hi @hughmcguire and @greatislander,

We recently embarked on parts a) and c), though with a bit less flexibility.  Here are some notes that may be of help.  I've broken them into two sections.  The first is specific to if you're going to allow in-language font filenames (for example, ヒラギノ明朝ProW3.otf).  The second is general notes on our approach.


========IF YOU'RE GOING TO ALLOW IN-LANGUAGE FONT FILENAMES========

  --When testing Chinese font filenames (like ヒラギノ明朝ProW3.otf) I spent a long time trying to make PCLZip work, but no matter what workaround I tried (mb_convert_encoding, iconv, etc)  it would always garble the filenames inside of the zip.  I also tried switching to ZipArchive and couldn't get that to work.  Ultimately I settled on calling the shell command for zip (we're on Ubuntu).  Here's a commit showing the approach.  Have to have the zip library installed but it's pretty straightforward.
  https://github.com/BBGInnovate/oddibooks/commit/91a5480b935960575664c787a4e18347689e41a1

  --We also had to loosen up the regex inside of scrapeKneadAndSaveCss because it wasn't catching Chinese characters (and presumably other UTF-8 chars may have issues).

========OUR GENERAL APPROACH========
  --We added a new token for fonts in the export stylesheets (let's call it /\*__INSERT_DYNAMIC_FONT__\*/)
  
  --we map languages to fonts in a new function our pb-utility.php file.  Sounds like you need something more flexible, but that's what we did since we were ok with hardcoding fonts on a language by language basis.
  
  --In the injectHouseStyles function (class-pb-export.php) we check the book's language and look up appropriate font info from our pb-utility function.  We then build up a string with up to 4 font-face declarations  (let's call them 'Dynamic_Sans' and 'Dynamic_Serif'.  It gets to 4 because if you include bolds).  We do a string replace on the /\*__INSERT_DYNAMIC_FONT__\*/ with the newly built string.
  
  --We refer to the name of the font-face rather than a hardcoded font-name later in the CSS files, but then fall back on regular font names as well in case a given reader doesn't support embeds

  --Although maybe not critical for you right now, keep in mind that mPDF is a separate beast in this regard since it wants fonts defined in config_fonts.php.  I talked a little about this here
  https://github.com/pressbooks/pressbooks/issues/190

Hope that helps

**Comment by hughmcguire** [comment]
We're likely to use SASS/Libsass ... we've been meaning to implement a server-side SASS pre-processor for a while, to make customizing templates on the fly a more sensible process. (We already use a SASS-based system for developing new themes). 

This will give us a specific, and relatively simple, usecase to test on ...

**Comment by greatislander** [comment]
@hughmcguire: send me a zip of all relevant language-specific fonts, as well as all relevant css snippets for the @font-face includes. Then I will get this underway.

@jflowers45 Thanks for the pointers! I'm hoping to have our implementation in the dev branch for testing in the next couple of weeks and will be happy to have your feedback on it.

**Comment by greatislander** [comment]
@hughmcguire In terms of integrating language fonts into existing theme CSS, e.g. https://github.com/pressbooks/pressbooks/blob/dev/themes-book/clarke/export/prince/style.css#L269, how do you want this to work?

For the editor style, it's easy enough because I can build the `body` font stack from scratch to include any required language fonts. However, for an arbitrary theme, I can't just insert another font into the `body` element's `font` attribute. Looks like something akin to @jflowers45 `/*INSERT_DYNAMIC_FONT*/` solution makes sense. But I would like it to be SASS-based. I think we need to discuss further.

**Comment by hughmcguire** [comment]
let's talk on slack.

**Comment by greatislander** [comment]
A clarification regarding Arabic: how do you want Noto Kufi Arabic and Noto Kufi Naskh to be distinguished for users? If we load both then the first one in the font stack will override the other. And they are stylistically different and often co-exist in the same regions (see [here](http://www.google.com/get/noto/#kufi-arab) and [here](http://www.google.com/get/noto/#naskh-arab)). Also we are using a different Arabic font in `pressbooks-adunis` (Amiri). Where does this fit in?

**Comment by hughmcguire** [comment]
I think list variants of language fonts as options: 
- Arabic (Kufi)
- Arabic (Naskh)

both can be selected, along with, eg. Coptic, Korean and Japanese, since any collection of fontsets might be needed in any given book.

now, on the user side ... how do they distinguish between Kufi or Naskh fonts ... in the editor?  Hrm. I guess, for starters, would need to add right font-selection mark-up ... ?

**Comment by greatislander** [comment]
Completed as a viable feature as part of #241.
