### ISSUE TITLE
Bug with newly exported EPUBs and Kindle file conversion

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks#2548]
### Description

When uploading a newly exported EPUB to Kindle Direct Publishing or opening it in Kindle Previewer, the automatic file conversion performed by Kindle introduces random characters like â€œ throughout the text. This issue has affected multiple users since the recent deployment of the new export routines. 

The random characters aren't present in an exported EPUB prior to Kindle's file conversion. However, EPUBs exported with the previous routine did not encounter this bug.

Normal appearance in an exported EPUB viewed in Calibre's e-book viewer:
<img width="372" alt="Screen Shot 2021-12-13 at 7 20 21 AM" src="https://user-images.githubusercontent.com/44182629/145838998-a931d57c-a697-426f-bb5c-4d3b517d0188.png">

Bug present in an EPUB opened (and automatically converted) in Kindle Previewer: 
<img width="334" alt="Screen Shot 2021-12-13 at 7 14 58 AM" src="https://user-images.githubusercontent.com/44182629/145838155-1b8561fd-5c1f-4d1e-8f11-194fa201dd94.png">

### Steps to Reproduce

1. Export an EPUB from Pressbooks.
2. Upload the EPUB to Kindle Direct Publishing or open it with Kindle Previewer.

**Expected behavior:** The book appears normally.

**Actual behavior:** Characters for apostrophes, hypens, and dashes are replaced with unexpected characters (like â€œ) throughout the book.

**Comment by SteelWagstaff** [comment]
Differences noticed after Calibre conversion:
1. HTML files inside chapter have extra line in doc declaration: `<?xml version='1.0' encoding='utf-8'?>`. HTML head also includes `<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>`
2. Calibre adds several files to root of package: content.opf, cover image, css stylesheets, titlepage, and toc.ncx. In our original, we have the book.opf file, toc.xhtml, and malala.css file inside the EPUB folder.
3. Calibre split a couple of chapters (002, 008, 016, part-004, and title-page)

**Comment by SteelWagstaff** [comment]
I think the most likely source of the problem is the absence of the charset encoding references. We were advised that we could remove `<meta charset>` element (which was unnecessary because the charset is declared in the XML declaration): https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/epub/templates/epub3/html.php#L14 + https://github.com/pressbooks/pressbooks/blob/9dcbdce9958422d564096778cab17091dd0a1cc2/inc/modules/export/epub/templates/epub201/html.php#L15 [https://github.com/pressbooks/pressbooks/issues/2425]

but it might make sense to restore this. See advice from EPUB3 best practices book from O'Reilly:
![Screenshot from 2021-12-13 09-10-38](https://user-images.githubusercontent.com/13485451/145857372-c30a2321-db0d-410f-bb2e-b5f433aa77c7.png)

**Comment by arzola** [comment]
Definitely is an encoding issue are you gonna send this PR @SteelWagstaff? or do you want me to try to fix it?

**Comment by SteelWagstaff** [comment]
@tw77 we merged a PR that should fix this issue. 
**To test**
1. Export an ePUB with accents and other encoded characters
2. Open the exported book in Kindle Preview and confirm that it was encoded properly
3. Open the book in Sigil to see if all the missing xml declarations were added

**Comment by tw77** [comment]
Tested new EPUB exports from integrations and textopress, opening the files in Kindle Previewer. Encoding is working properly here: no random characters are appearing after Kindle's file conversion. Compared with recent EPUB exports from pressbooks.com to confirm the difference.

Opened new EPUB exports from integrations and textopress in Sigil. The necessary XML declarations are included.

This fix is ready for the next deploy.
