### ISSUE TITLE
Instruct the cloning routine to apply the source book’s theme and theme options and import any custom styles if the theme versions are identical

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2576]
Instruct the cloning routine to apply the source book’s theme and theme options and import any custom styles if the theme versions are identical (maybe as part of postProcess?) https://github.com/pressbooks/pressbooks/blob/51dce1a0387545602e5d5c1bda461261a993bff4/inc/cloner/class-cloner.php#L495
* If successful, display the following message: "Cloning succeeded! Cloned ... and x glossary terms to BOOK TITLE. The source book's theme, theme settings, and custom styles were successfully applied." (bolded text is new):
* If the target book’s theme is not available on the source book’s network, apply the network’s default theme to the newly cloned book and display the following message: "Cloning succeeded! Cloned ... and x glossary terms to BOOK TITLE. The source book's theme, 'THEME NAME (version)', was not available on this network and could not be applied. Contact your network manager with questions about theme availability." (bolded text is new)
Cloning success message is generated here: https://github.com/pressbooks/pressbooks/blob/51dce1a0387545602e5d5c1bda461261a993bff4/inc/class-eventstreams.php#L200-L212

**Comment by tw77** [comment]
Tests so far:

Cloning within Integrations works, bringing over themes, theme options and custom styles. 

Cloning from Integrations to Textopress (where the source theme is available) also works, bringing over theme, theme options and custom styles.

Cloning from Textopress to Integrations (where the source theme is not available) gets the expected result. We see the message about the theme not being available. The book clones without bringing over the theme, theme options or custom styles.

I see that the University network doesn’t have this new cloning feature yet, so when I clone a book from Integrations to University, the cloned book is created but the theme, theme options and custom styles are not applied.

I also notice that cloning a book _from_ University to Integrations doesn't result in the theme, theme options or custom styles being applied. This may be expected, but just to confirm, both networks -- the network with the source book, and the network where the clone is created -- appear to need to have this new routine set up in order for a clone to bring over the theme, theme options and custom styles from the source book.

**Comment by tw77** [comment]
Confirmed the above.

When cloning a book with an older version of a theme to a network with a newer version of the theme, this is handled as an unavailable theme:

<img width="1074" alt="Screen Shot 2022-01-26 at 12 11 11 PM" src="https://user-images.githubusercontent.com/44182629/151240946-74406df6-4da1-4f33-b434-3a2513890ebc.png">

Same with cloning a book with a newer version of a theme to a network with an older version of the theme:

<img width="1072" alt="Screen Shot 2022-01-26 at 12 17 31 PM" src="https://user-images.githubusercontent.com/44182629/151241139-895b3afe-35f5-4f0b-a35d-622ee29edf95.png">

There's a missing space after the end of the second sentence in this notice.

Another test: cloning a book with a theme that is available but not active on a network successfully brings over the theme, theme options and custom styles. As @fdalcin has noted, one detail here is that if a user then changes their cloned book to a different theme, they won't be able to change the theme back to the source book's theme because it isn't active on the network. This would be potentially resolvable through contacting a network manager.

**Comment by tw77** [comment]
Aside from that tiny detail with the missing space, no issues found here.

- Cloning a book in-network always works with this feature with a range of different themes + theme options (global, web, PDF, ebook) + custom styles.

- Cloning a book to a different network that also has this feature also works every time, bringing over the theme + theme options + custom styles. It's also possible to clone a book to a network where the source book's theme is available but not active. The theme + theme options + custom styles are still applied here.

- When cloning from networks with this feature to networks without this feature, and vice versa, the book still clones normally, just without bringing over the theme + theme options + custom styles.

- When cloning a book to a network where the source book's theme is unavailable or only available in a different version, the book clones normally, just without bringing over the theme + theme options + custom styles.
