### ISSUE TITLE
s&r error ... replacing "serif" with "$serif"  

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#262]
hey ned, you've made a search & replace error (I think), eg in this file:

https://github.com/pressbooks/pressbooks/blob/aa77bce0599731335ca2e856470ae889b083e429/themes-book/austen/_mixins.scss

... this: 

`$font-stack-2-prince: "Marcellus SC", $serif;`

should be this:
`$font-stack-2-prince: "Marcellus SC", serif;`

happening in many files.

this is messing up all outputs, EPUB & PDF.

**Comment by greatislander** [comment]
There needs to be a variable there, otherwise there's no place for the global font stack to be inserted.

The $serif variable definitely exists! It's set [here](https://github.com/pressbooks/pressbooks/blob/dev/includes/class-pb-globaltypography.php#L88):

```
		if ( strpos( $font_stacks, '$sans-serif' ) !== false ) {
			$global_font_stack_sans = '$sans-serif: ';
			$sans = true;
		} else {
			$global_font_stack_sans = '$sans-serif: ';
		}
		 
		if ( strpos( $font_stacks, '$serif' ) !== false ) {
			$global_font_stack_serif = '$serif: ';
			$serif = true;
		} else {
			$global_font_stack_serif = '$serif: ';
		}
```

Then the font stack is populated based on whether or not any languages were selected for inclusion and written to the uploads directory as a SASS file for inclusion ([here](https://github.com/pressbooks/pressbooks/blob/dev/includes/class-pb-globaltypography.php#L340-L344)).

The problem was that if there are no languages, `$serif` was being set to a blank variable instead of `serif`, so SASS was compiling:

```
$font-stack-2-prince: "Marcellus SC", : ;
```

instead of…

```
$font-stack-2-prince: "Marcellus SC", serif;
```

Fixed in 936655a8eab259b24fefaf5e85564f3bd1b785bb.
