### ISSUE TITLE
Code Review \PressBooks\Modules\Export\WordPress\VanillaWxr::convert

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#279]
Hi brad, can you review

https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/wordpress/class-pb-vanillawxr.php#L66

Line ~66

```php
		for ( $i = 0; $i = $term->length; $i ++ ) {
			$this->deleteNode( $term->item( 0 ) );
		}
```

Second param in for() should be `==` or `<=` or `>=`but not `=` which is a typo and overwrites the value? If I fix this I'm afraid of breaking the current behavior which may be desired. I don't understand the code. What does this do?

**Comment by bdolor** [comment]
As object nodes are deleted from `$this`, the numeric value of `$term->length` decreases by one on every iteration of the for loop. Since `$i` is given its value (45, 44, 43, 42, etc) it functions as a limiter. When `$term->length` starts off as `45` and if you modify the operator to `<=` you will only iterate through 22 times, for instance.

For the sake of clarity, the same effect could be achieved thus: 
`		
$length = $term->length;
for ( $i = 0; $i < $length; $i ++ ) {
`...

**Comment by connerbw** [comment]
Awesome, thanks!
