### ISSUE TITLE
Add capability to link to internal anchors/IDs

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#294]
Via core "add link" modal, or…?

**Comment by greatislander** [comment]
From @hughmcguire on #301:

Button(s) allow user to:
-- add an ID to an element
-- link to that element from within the page

ANCHOR SPEC:

highlight content, select “add anchor”
insert link, select “Or link to existing content” (<< using existing LINK tool, or with new Anchor link button)
add a selection of “Link to Content in this page” … which lists IDs in the page to link to, inserts correct markup.
NOTE: 
-- need to make sure paths work in all exports 
-- make sure paths work properly on:

book.pressbooks.com as well
clientsite.pressbooks.pub/book

**Comment by greatislander** [comment]
Okay, I'm going to use the built in link selector for this. Before I start working on the functionality, are we only looking to link to anchors within the existing chapter/front/back matter, or do we need to scan the entire book for anchors?

**Comment by greatislander** [comment]
This is done.

**Comment by greatislander** [comment]
FYI @hughmcguire

**Comment by greatislander** [comment]
This is how it works. First you use the Anchor button to add the anchor (target) for internal linking. Then you use the Link button to select the target you've added.

<img width="1071" alt="1" src="https://cloud.githubusercontent.com/assets/605361/12360034/c85fb094-bb8b-11e5-9d2f-39fbe743d003.png">
<img width="787" alt="2" src="https://cloud.githubusercontent.com/assets/605361/12360037/ca463d38-bb8b-11e5-8910-8f70be08cb0a.png">
<img width="562" alt="3" src="https://cloud.githubusercontent.com/assets/605361/12360038/cc02521a-bb8b-11e5-9f0a-97a7cdc63151.png">

**Comment by hughmcguire** [comment]
hi ned,

OK there is some problem with how the anchor tool works (was there before us).

Expected behaviour: 
1. I highlight text (say: `"my pal ben" is a nice guy`) 
2. I press anchor button 
3. i add an anchor name: "anchor1"
4. i save me new anchor
5. an anchor tag with ID is wrapped around the text i highlighted 

... so I would expect: 
`<a id="anchor1">my pal ben</a> is a nice guy`

Actual behavior: 
1, 2, 3, 4, ... "my pal ben" gets deleted so we get:
`<a id="anchor1"></a> is a nice guy`

Similarly, if the source text is: 

`<h2>My pal ben</h2>
Is a nice guy`

and I wrap the same text, I would expect either: 

`<h2 id="anchor1">My pal ben</h2>
Is a nice guy`

Or, worse case: 
`<a id="anchor1"><h2>My pal ben</h2></a>
Is a nice guy`

BUt instead we get: 
`<h2></h2>` ... so the text inside the `h2` tags is deleted AND we don't get an anchor.

**Comment by greatislander** [comment]
Technically,

**Comment by greatislander** [comment]
The way the TinyMCE anchor plugin works is described here. I will have to write a new one from scratch to get that functionality:

https://www.tinymce.com/docs/plugins/anchor/

**Comment by greatislander** [comment]
Specifically:

> When a user clicks on the anchor button or menu item they will be prompted via a dialog box to enter a string. The string will be inserted into the HTML as an anchor id at the location of the cursor. For example, a user places their cursor at the beginning of "Hello World" and clicks on the anchor button and enters "start" in the dialog box. The resulting HTML will take the form of `<p><a id="start"></a>Hello, World!</p>`.

**Comment by hughmcguire** [comment]
ug.

**Comment by greatislander** [comment]
You're not supposed to invoke it with a selection… :wink:

**Comment by hughmcguire** [comment]
ok working more or less as expected. however there are multiple instances of the internallinks in the dropdown in test instance.

also: is there anyway to "sort" internal links in the dropdown?

**Comment by hughmcguire** [comment]
tested just now and the links are not getting doubled. so maybe it's OK to push out.
