### ISSUE TITLE
Create health check API endpoints

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#2985]
Create health check API endpoints to help with infrastructure monitoring. Os proposes making a new plugin managed by composer for this. Could be a small Laravel app.

Do a set of tests: returns either an OK or an error message. 

Check DB connection, redis/cache connection, file system space remaining, availability of main site API

**Comment by fdalcin** [comment]
Created a draft PR so we can discuss about cache approach and other improvements.

**Comment by fdalcin** [comment]
PR adds a new endpoint to the network API - `{NETWORK_URL}/wp-json/pressbooks/v2/health-check?_token={PB_HEALTH_CHECK_TOKEN}`.

**Deploy**
@cmurtagh @ho-man-chan when deploying this to a network, it's necessary to create a new  `PB_HEALTH_CHECK_TOKEN` environment variable with a random string that will be used to authorize the endpoint to be used

**Test**

- When testing it's important to validate the new endpoint fails if the `_token` parameter is missing or is not the same stored in the `.env` file.
- If a valid request is sent, it's important to check if the checks respond as expected (you can disable the cache for a while to see a check failure for example)
- It's important to validate `{NETWORK_URL}/wp-json/wp/v2/users` endpoint returns a 404 response and does not expose user data anymore
- Performing a complete test for clone/import/export routines would also be desired since this touches API and could cause unexpected impact.

**Comment by fdalcin** [comment]
**Health check endpoint**

- [x] Fails with no token parameter
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1761690/202199013-8a8d7bc4-4cab-43b3-afab-567cfe1e7c15.png">

- [x] Fails with empty or invalid token parameter
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1761690/202199201-43d6aff8-1331-4514-a79a-c6cb5d10affe.png">
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1761690/202199308-cd161f9b-7963-401d-a32e-0ba2f70ef26a.png">

- [x] Respond properly when using the correct token
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1761690/202199511-52cd7620-1240-40cc-91be-ac2c6426aa8f.png">

- [x] Respond properly if something is wrong
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1761690/202199727-07eb71e9-bb80-4e84-b1fa-d12f7b233432.png">

**Users endpoint**

- [x] GET request is disabled and the API only respond to other HTTP verbs when available
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1761690/202200086-a7c3ed68-629a-4532-9b10-4d38e05b2295.png">
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1761690/202200270-cd5fb27f-b9dd-477c-84bc-bef479e28658.png">

**General testing**

- [x] Clone routine is working - same network
- [x] Clone routine is working - different network 
- [x] Export routine is working
