### ISSUE TITLE
Make Pressbooks compatible with WordPress 6.1

### ISSUE THREAD

**Issue by arzola** [pressbooks/pressbooks#2986]
Pressbooks is not yet compatible with WordPress 6.1. See https://pressbooks.community/t/just-stopped-working/2185 for initial reports from open source users who ran into problems after upgrading to WP 6.1 (released on November 1)

When testing locally, logged users see a `502 Bad Gateway / nginx` error after upgrading. After clearing the cookies, public pages on the local installation load normally, but after entering their username/password, the user sees the 502 Bad Gateway error instead of the expected admin menu.

Deactivating pressbooks/pressbooks allows users to successfully login and see the WP multisite admin menu.

**Comment by greatislander** [comment]
I've been testing this and the out of memory error _seems_ to be related to an infinite loop caused by this line of code: https://github.com/pressbooks/pressbooks/blob/05a33e0d0221ad0ed23521280d4d4ca13d405d61/inc/l10n/namespace.php#L410

This is part of the function which overrides certain core UI strings (such as `View Site`) with Pressbooks-appropriate equivalents (e.g. `View Book`). It is loaded via this hook:

https://github.com/pressbooks/pressbooks/blob/05a33e0d0221ad0ed23521280d4d4ca13d405d61/hooks.php#L105

**Comment by SteelWagstaff** [comment]
Tested with 6.1.1 today. Appears ready for release to me.
