### ISSUE TITLE
Build better 'book dashboard'

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3018]
We want to replace the default book dashboard users see when visiting their book's admin panel at `https://NETWORKURL/BOOKRURL/wp-admin`. 

See https://www.figma.com/file/DDZ7YuklYsX9AAyVc5caUv/User-Dashboard?node-id=202%3A4&t=q74nQNytzGXTkWiT-0 for wireframe.

**Comment by tw77** [comment]
Testing shows that all links are working and the dashboard layout adjusts smoothly when resizing the window. The appropriate links are shown for each user role with one possible exception. Subscriber users don’t see the book cover and ‘View Book,' which may be intentional, but it makes it difficult to navigate to the book from the dashboard, since only this method is available:

<img width="1270" alt="Screenshot 2022-12-08 at 10 03 08 AM" src="https://user-images.githubusercontent.com/44182629/206533104-edbda2a2-642c-42a8-be48-1f79177fe076.png">
