### ISSUE TITLE
Create new dashboard for network managers

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#3150]
As a super admin or network manager, I want to see a clear welcome page that orients me with the key activities I can take a network administrator.

If I am an super admin/network manager, this is the first page I should see upon login to the network (instead of the new user dashboard). This network manager dashboard should replace what network managers currently see as their 'network admin dashboard' at https://MYNETWORKURL/wp/wp-admin/network/. It can have a new page specific URL.

This dashboard should be visible to open source users and clients alike. In cases where the pressbooks network analytics plugin is not active (and the custom book & user list or settings/stats pages are not available), links should point do the default pages instead. See Figma comments for more details.

## Design notes
See the Figma wireframe: https://www.figma.com/file/CU0d5QeDcCRK9LK2xUuYQp/Network-Manager-Dashboard?node-id=640%3A503&t=m955UZbuNqroGbCK-0 for desired content & appearance. See written recommendations for the dashboard here: https://docs.google.com/document/d/1227gW5CmccJNUhxfTduViB3kkKpzJKd_UdWP49oE5pk/edit#

**Comment by fdalcin** [comment]
New branch created with the work in progress for this task, see https://github.com/pressbooks/pressbooks/tree/feat/new-network-dashboard

**Comment by fdalcin** [comment]
@SteelWagstaff draft PR created here https://github.com/pressbooks/pressbooks/pull/3175., feel free to submit any styling/copy changes. The css file is the same one from previous dashboards and it's located at `assets/src/styles/pressbooks-dashboard.scss`.

**Comment by SteelWagstaff** [comment]
Only thing missing are the desired heroicons. We'll add those when we do the sidenav. Should be ready for testing and feedback from Thomas, Michelle, and anyone else who has opinions!

**Comment by tw77** [comment]
I like this. All links work as expected.

I anticipate some premium support questions about the text "View web analytics" because it might inadvertently suggest updated functionality. Since the analytics at that link are for the home page and related ("root site") pages, rather than books on the network, I wonder if "View home page analytics" might be more clear? Of course, this is already implied since the "View web analytics" link is in the "Update your home page" block. But I think "View web analytics" might still be interpreted as linking to analytics for books on the network as a whole (or the kind of data that is actually found at the Stats page).

**Comment by SteelWagstaff** [comment]
@tw77 & @MichelleWeremczuk changes you recommended to copy and image size have been made. They look good to me. Any further suggestions? @tw77 and @pb-amy we have a problem in the support resources section. Initially I thought we'd link to the Pressbooks spotlight series -- but there aren't any future webinars in this series scheduled. What should I link to here? Webinars in general? YouTube channel? Something else? 
![Screenshot from 2023-02-15 16-28-46](https://user-images.githubusercontent.com/13485451/219226891-faceb830-547f-4569-b7bf-67fc997c984b.png)
