### ISSUE TITLE
Set up correct dashboard redirect depending on user role

### ISSUE THREAD

**Issue by fdalcin** [pressbooks/pressbooks#3195]
With the creation of the new dashboards ([network](https://github.com/pressbooks/pressbooks/pull/3175), [book](https://github.com/pressbooks/pressbooks/pull/3059), and [user](https://github.com/pressbooks/pressbooks/pull/3048)) we started redirecting users to the new user dashboard by default, [see](https://github.com/pressbooks/pressbooks-aldine/pull/384/files).

As a Super Admin or Network Manager, I'd like to be redirected to the new network dashboard by default.

The expected behaviour should be as follows:

| Role | Signing in from root site | Signing in from book page |
| :--: | :-- | :-- |
| Regular user | redirect to the new user dashboard | redirect to the respective book page |
| Network manager | redirect to the new network dashboard | redirect to the respective book page |
| Super admin | redirect to the new network dashboard | redirect to the respective book page |

**Definition of done**

When signing in users are redirected to the expected page as described above.

>**Note**
For reference I've found this hook that we already use to fix a WP bug. We could use the same method to handle both situations or create a second hook that runs right after this one. Also, it would be worth checking if WP has fixed this bug already :)

https://github.com/pressbooks/pressbooks/blob/688c9847c55b4824d299a30149f7653990d720d1/hooks.php#L181
https://github.com/pressbooks/pressbooks/blob/38b69cb3b9ec488dd2ea0202e35c7f929ec1519e/inc/redirect/namespace.php#L467-L494

**Comment by tw77** [comment]
Tested on dev.presssbooks.network. The expected behaviour outlined above occurs as described for each role and sign in location.

This may be out of scope, but the one unusual thing I noticed during testing is that if a regular user signs in from a private book that they aren’t a user on, they’re returned to the same Access Denied page while logged into the network:

<img width="1440" alt="Screenshot 2023-02-22 at 7 50 53 AM" src="https://user-images.githubusercontent.com/44182629/220681279-4dccfff8-e92c-442c-8d86-3f30d3fed061.png">

In this situation, the "sign in here" linked text redirects them to the same (Access Denied) page.

This is potentially confusing for users who do have an account on a network and who expect to have access to a private book but aren't a user on it yet. The generic Access Denied page seems to imply that they either aren't a registered user on the network or aren't logged in yet, but they are a logged in user.

A specific Access Denied private book page for a user who is signed into the network but isn't a user on a given book would solve this. Perhaps it could contain linked text linking to the user dashboard? But this might be a separate ticket.
