### ISSUE TITLE
https://github.com/pressbooks/pressbooks/releases/tag/6.9.0 leads to error 404

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#3210]
### Description

https://github.com/pressbooks/pressbooks/releases/tag/6.9.0 leads to error 404

### Steps to Reproduce

Go to: https://github.com/pressbooks/pressbooks
click the link for Release 6.9.0: https://github.com/pressbooks/pressbooks/releases/tag/6.9.0 
error 404 is shown

### Expected behavior
release 6.9.0 is shown

**Comment by SteelWagstaff** [comment]
This is because we haven't released 6.9.0 yet. The dev branch includes the latest experimental commits to our repos. See https://pressbooks.org/dev-docs/branch-workflow/. You can see the latest stable, tagged releases in the 'releases' for a given repo. In the case of pressbooks/pressbooks, we're still working on the 6.9.0 release -- we simply updated the readme in the dev branch to reference the forthcoming release.
