### ISSUE TITLE
Implement autosave in Pressbooks

### ISSUE THREAD

**Issue by arzola** [pressbooks/pressbooks#3268]
As an author, I'd like in progress work to be auto-saved while in progress, so I don't lose my work if my browser crashes or internet connection is disrupted. 

### Feature Description
WordPress core has an autosave feature, in which drafts of posts/pages are automatically saved to the database as part of the revision history based on the AUTOSAVE_INTERVAL defined in the `wp.config.php` file. See https://jetpack.com/blog/wordpress-autosave/ + https://www.wpbeginner.com/glossary/revisions/

Pressbooks used to support this feature (I believe), but autosave appears to be broken, and is only triggered now when users 'preview' or 'save' their posts. See https://github.com/pressbooks/private/issues/1019#issuecomment-1284035146

Autosave in WordPress relies on 'Heartbeat': https://make.wordpress.org/core/2013/01/19/autosave-and-post-locking/. When we refactored the cloning page to allow users to clone from anywhere, we deregistered heartbeat on all admin pages instead of just the cloning page. See: https://github.com/pressbooks/pressbooks/commit/6677e6a32882493247473158aa4c049ae69a6e5e. If we were to only remote heartbeat from the cloning page, that should resolve this issue. See https://github.com/pressbooks/pressbooks/issues/3258 (open source user confirmed they could restore autosave functionality by commenting out this line: https://github.com/pressbooks/pressbooks/blob/7b7d3be450880c6af5cec7826142bc3c987e673e/inc/admin/laf/namespace.php#L638

### Other Notes

Some of our users were confused when autosave disappeared from Pressbooks, and were disappointed when they lost work beacuse the feature was no longer present.

Autosaving appears to work normally for me in the classic editor of my vanilla WordPress multisite install, which leads me to believe that it's not working in Pressbooks either because of our use of custom post types or because of how we've modified the core WordPress 'publish' block. 

WP core maintainers aren't aware of any problems with core WP related to this either:
![Screenshot from 2023-01-26 08-55-06](https://user-images.githubusercontent.com/13485451/214898871-107c1f40-c745-46ce-9ad2-b8f1b14037f3.png)

There is a plugin called [wp-autosave](https://wordpress.org/plugins/wp-autosave/?ref=commonninja) that adds the feature but is not working properly with our custom post types. We can update or fork the `wp-autosave` plugin in order to implement this feature for our users

**Comment by SteelWagstaff** [comment]
Talked with @fdalcin about this. We need to add a check to only add pb-clone scripts and remove the heartbeat scripts on the cloner page, instead of all admin pages. Compare https://github.com/pressbooks/pressbooks/blob/7b7d3be450880c6af5cec7826142bc3c987e673e/inc/admin/laf/namespace.php#L616-L628 with https://github.com/pressbooks/pressbooks/blob/7b7d3be450880c6af5cec7826142bc3c987e673e/inc/admin/laf/namespace.php#L352-L355 or https://github.com/pressbooks/pressbooks/blob/7b7d3be450880c6af5cec7826142bc3c987e673e/inc/admin/laf/namespace.php#L412-L416

**Comment by SteelWagstaff** [comment]
PR open and ready for review, if you're willing @richard015ar

**Comment by SteelWagstaff** [comment]
Autosave works again in dev.pressbooks.network (yay!). However, the contents of the head and body elements of admin pages look odd. Not sure if this is because of the deprecation notice of something else. It isn't broken in staging or production networks. Compare https://dev.pressbooks.network/wp/wp-admin/index.php?page=pb_home_page
![Screenshot from 2023-04-11 12-27-09](https://user-images.githubusercontent.com/13485451/231268483-b1b767ba-0433-4da2-9e13-575cd29bd983.png)

(styles and scripts are being inserted at the top of the body element instead of in the head as expected)
with https://integrations.pressbooks.network/wp/wp-admin/network/admin.php?page=pb_network_page
![Screenshot from 2023-04-11 12-25-16](https://user-images.githubusercontent.com/13485451/231268103-ece56fff-0b30-4f38-ab50-71f3d041b2ba.png)
(styles & scripts are inserted in the document head not the body).

**Comment by fdalcin** [comment]
This is due to the fact that the dev environment displays warnings like the deprecation ones. Locally I don't see this issue happening unless I display debugging messages or warnings. See below:

**Output without warning messages**
![image.png](https://images.zenhubusercontent.com/60a7e6a889e8274a68d8c65b/195969c2-79c3-426c-945d-68a58021a389)

**Output with warning messages**
![image.png](https://images.zenhubusercontent.com/60a7e6a889e8274a68d8c65b/18dde95d-dd77-4ab1-b579-364430310cf9)

**Comment by SteelWagstaff** [comment]
This happens in my regular bedrock-based Pressbooks install with vanilla WP as well:
![Screenshot from 2023-04-12 07-04-35](https://user-images.githubusercontent.com/13485451/231482713-30ebaf44-2b54-4b3c-8d90-3603e04d90bd.png)
