### ISSUE TITLE
create access to General Settings from PB dashboard

### ISSUE THREAD

**Issue by JackDougherty** [pressbooks/pressbooks#344]
Perhaps I'm overlooking something, but PB seems to lack a convenient way to access the General Settings page of the site to set the timezone (aka wp-admin/options-general.php). See screenshot.

I arrived at this WP page from a link on my Backupbuddy plugin, but don't see a PB button that takes you there.

![general_settings_ _pressbookstest_ _pressbooks](https://cloud.githubusercontent.com/assets/649719/12519153/0ecb4244-c10b-11e5-866b-106d5eb58d34.png)

**Comment by greatislander** [comment]
Hi @JackDougherty—the reason we hide this globally is because there are a lot of settings we don't want modified on a per-book level for large networks (are main criteria for development choices is usually—will this cause confusion or problems for the 20,000+ books on pressbooks.com? if yes, we don't do it). The site name and tagline are not used by Pressbooks, which causes confusion, and the book language is set in Book Information so that we are not limited by WordPress' list of available languages (which is quite small). To clarify your request—are you interested in being able to set the time zone for your whole network, or an individual site? I could see that we might enable this for the root site only (it's my understanding that root site timezone settings apply to all subsides in a network: https://wordpress.org/support/topic/network-timezone-setting). Let me know if this would address your issue. I can't see us supporting timezones for specific books, but this might be doable.

**Comment by greatislander** [comment]
(FYI @hughmcguire.)

**Comment by JackDougherty** [comment]
Thanks @greatislander for the explanation. As the admin of my self-hosted site, I now know how to find this timezone setting. My suggestion is simply to make it easier for other self-hosted admins to see and adjust this setting for the root site, if you think it would be useful and easy to do. That's all.

**Comment by greatislander** [comment]
@JackDougherty I haven't forgotten about this—I'm moving it over to https://github.com/pressbooks/pressbooks-publisher/issues/7
