### ISSUE TITLE
investigate QuickLaTeX instead of WP-LaTeX plugin

### ISSUE THREAD

**Issue by hughmcguire** [pressbooks/pressbooks#348]
see:
http://www.holoborodko.com/pavel/quicklatex/

**Comment by advanpix** [comment]
Good idea. QuickLaTeX allows functionality of a complete LaTeX distribution (TexLive) to be used in WordPress, including generation of plots in SVG.  Actually few online books are using it already - good idea to try it for pressbooks.

(I am author of QuickLaTeX)

**Comment by advanpix** [comment]
Something like this (seminar notebook): https://blogs.princeton.edu/sas/
Not only the formulas, but also all the plots on the page are generated by QuickLaTeX.

**Comment by hughmcguire** [comment]
@advanpix great to hear from you ... maybe we could have quick chat sometime? I can tell you what we are doing, why etc. ;-) 

Our constraint is the following: 
Pressbook is a book production tool, built on WordPress ... we output:
- WEB books (see, eg: http://book.pressbooks.com)
- EPUB 
- MOBI
- PDF (using PrinceXML.com) ...

So we need to be careful about not just browser rendering of SVG, but exports into EPUB (which sometimes supports SVG), MOBI (which sometimes supports SVG), and Prince/PDF which does support SVG.

So, if we move to QuickLaTeX we need to intelligently manage the different outputs.

**Comment by advanpix** [comment]
We generate images in SVG and in PNG formats. In old browsers we use PNG, SVG is for new ones.
I think PNG is supported in all software in your list.

However for better quality with PDF, images should be rendered in PostScript. We can add this feature to QuickLaTeX, if you decide going this way.

**Comment by JimBrouzoulis** [comment]
**Some comments:**
I have tested QuickLaTeX on my own PB installation with mPDF and the results are comparable with WP-LaTeX. However, since QuickLaTeX allows an SVG option the equations in the generated PDF is much sharper (acceptable quality). The .png converted images from both plugins produce too low quality images in the final PDF and cannot be used.

For some reason I cannot convert to MOBI and EPUB using my own installation (no output generated), where can I find an error log?  

Using my PB-account I have generated MOBI + EPUB - PDF containing math using WP-LaTeX, with the follwing results:
EPUB: No equations are displayed but are replaced by an "empty page" icon
MOBI: Some equations are displayed while others are replaced by an "empty page" icon. The quality is low on the equations that are actually shown.
PDF (Prince): All equations are shown (but with too low quality as mentioned above). There is also a vertical misalignment of several equations. I guess additional QuickLaTeX-CSS needs to be included when compiling using Prince. The same problem was observed when using mPDF.

**Short summary:**

- WP-LaTeX do only produce acceptable results for the Web-version and is broken for MOBI and EPUB.

- WP-LaTeX (Prince) and QuickLaTex (mPDF) seems to produce similar visual output for PDF but png converted equations have too low quality. 

- QuickLaTeX has support for SVG which produces OK quality in PDF.

- Output for EPUB and MOBI not checked for QuickLaTeX
 
- Formatting issues (vertical misalignment of equations, centered equations flushed left, etc.) regardless of output format and plugin used (CSS classes probably not included).

At the current state I would say that Quick-LaTex should replace WP-LaTeX since it produce higher quality output with more flexibilty (e.g. custom preamble and Tikz-figures).

**Comment by advanpix** [comment]
I can only add that it has sense to compare not only the output formats (PNG, SVG, etc.) but also the functionality. QuickLaTeX gives access to full LaTeX distribution with hundreds of packages, etc. (~5 GB), whereas WP-LaTeX provides only trivial functionality - basic formula rendering, even without proper vertical alignment.

**Comment by hughmcguire** [comment]
thanks for the feedback. we'll be looking at all this shortly. @advanpix: we'll likely have questions ;-)

**Comment by connerbw** [comment]
Right, but with the full LaTeX distribution you can publish a book so why use Pressbooks at all?

Let's not forget that Pressbooks, at one time long ago, used LaTeX as it's PDF rendering engine. Code for this still exists in includes/shortcodes/wikipublisher/class-pb-glyphs.php. The problem with doing his is that these features and the LaTex syntax translated poorly, if at all, to web and ebook.

Pressbooks is a publishing platform that has a primary design goal to normalize book outputs to HTML+CSS. LaTeX should be used for things that HTML+CSS cannot do on it's own.

**Comment by hughmcguire** [comment]
HTML+CSS still can't do math equations (since MathML is a) not well suppported, b) authoring is not easy.

With Pressbooks you get: 
* the ease of a familiar web-based (WP-based) editing platform
* well-designed PDF/EPUB/MOBI formatting (with a built in understanding of book structure)
* a native web output out of the box

If you add support in PB for a LaTeX equation editor (which we already have, though apparently it is not working properly) ...you add: 
* Support for the most well-known math equation editing language in addition to the above.

If people want to write their books in LaTeX, and not PB, they should do that.
 
For those who want to write in PB, and need math equation support, we need to add that support if there are good tools to do so (especially as Open Textbooks are a main focus of our dev roadmap). We currently support WP-LaTeX (which appears to be sometimes-working) ... and the discussion here is about using a different/better plugin to support clear needs from users.

**Comment by connerbw** [comment]
Terrific. I'm excited for PB improve support for the most well-known math equation editing language.

I'm not so much excited about the idea of installing and supporting 5GB of LaTex functionality on PB servers, which was a pain point we moved away from in V2.

Cheers.

**Comment by greatislander** [comment]
@connerbw Sure, but… that is not the plan. QuickLaTex uses a full, externally-hosted LaTex distribution. From the [plugin readme](https://wordpress.org/plugins/wp-quicklatex/), first paragraph:

> No LaTeX installation required.

This is preferable to our current implementation because:

1. Intelligently supports both SVG and PNG;
2. Uses a full LaTex distribution as opposed to the limited WordPress.com one, and thus supports more advanced outputs.

Bonus: it's backwards compatible with equations inserted using the WP-LaTex shortcodes.

**Comment by hughmcguire** [comment]
With negative: it means PB users of this tool are dependent on an external service ...  but in theory, PB's open architecture should mean that users could access whatever external tools they need, and have those intelligently plug into PB ... in theory anyway.

**Comment by greatislander** [comment]
> it means PB users of this tool are dependent on an external service

Which they already are (WordPress.com/Automattic's LaTex server).

**Comment by stepmuel** [comment]
@greatislander having noticed your special switch for QuickLaTeX, couldn't you (also) do a more general solution to disable PB-LaTeX, e.g. by defining something in wp-config.php? There are a lot of different LaTeX plugins people might want to use instead of the PB one; handling each of them separately doesn't seem the best solution. (I'm currently overwriting the shortcode handler to deactivate it.)
