### ISSUE TITLE
Question about the fonts

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#365]
Pressbooks it is a zip file with 184MB. But if you open the file, the problem i think is the NotoSans Font. I don´t know how important is that font, but take a look

![captura de pantalla 2016-03-05 a las 16 13 35](https://cloud.githubusercontent.com/assets/3929177/13548299/4e66f19c-e2ed-11e5-8631-2b65e3e750f7.png)

Mabybe is really important, and we need to use it if we want to be able to sync acros devices, i don´t know about fonts. But maybe you could make it as the pdf option, a new plugins just for the fonts. 

Because each time we make a backup, it takes longer + more space. It will be faster and simple if the fonts are available from other place.

or import from google fonts: https://www.google.com/fonts/earlyaccess

thanks

**Comment by greatislander** [comment]
Hi @colomet—please read the [Contributing Guidelines](https://github.com/pressbooks/pressbooks/blob/dev/CONTRIBUTING.md) and use the issue template to submit new issues—having a standard format for issues helps us respond more efficiently.

Noto Sans fonts have to be present for multilingual support—specifically non-Latin character sets. We can't import them from Google Fonts because of the way the export routines work require the font files to be locally available. In theory, it would be possible for them to be downloaded on demand (e.g. when a book's language is set to Japanese, Pressbooks downloads the Japanese font set) but this isn't a feature that the core Pressbooks team has the development resources to implement right now. We would welcome pull requests that achieved this functionality, as long as they conform to our [Contributing Guidelines](https://github.com/pressbooks/pressbooks/blob/dev/CONTRIBUTING.md).

For your purposes I would suggest setting up an exclusion pattern for your backups so that files matching…

`/wp-content/plugins/pressbooks/themes-book/pressbooks-book/fonts/NotoSansCJK*`

…are excluded from backups.
