### ISSUE TITLE
Make internal links (within book) be relative to sections and chapters

### ISSUE THREAD

**Issue by rootl** [pressbooks/pressbooks#371]
### Prere
* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)? YES
* [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)? YES
* [x] Are you experiencing this issue with one of our built-in root or book themes? YES
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?  YES

### Description

Can links within a book be made relative to book sections and chapters?   We will have our books hosted on other servers and would like all internal links to be relative and not include a full url.

For example a link on the page http://pressbooks.opensuny.org/concise-introduction-to-logic/front-matter/introduction/
Structured as an internal/relative link “../chapter/17/” cannot locate the resource and registers as a broken link.

### Steps to Reproduce

1. [First Step]  http://pressbooks.opensuny.org/concise-introduction-to-logic/front-matter/introduction/
2. [Second Step] Structured as an internal/relative link “../chapter/17/” cannot locate the resource and registers as a broken link.

**Expected behavior:** [What you expected to happen]  Would like internal likes to be made relative to book sections and chapters;

**Actual behavior:** [What actually happened]    Link is broken

### Themes

Root Theme: [Enter the root theme you are using here, e.g. "Pressbooks Publisher"] Pressbooks Publisher; also with custom root theme
Book Theme: [Enter the book theme you are using here, e.g. "Luther"]  Luther; tried with all themes

### Versions

Pressbooks: [Enter Pressbooks version here]  3.2
WordPress: [Enter WordPress version here] 4.4.2
PHP: [Enter PHP version here] 7

You can get the version of Pressbooks from the readme.txt file in the Pressbooks plugin (usually located at `http://<yourdomain.tld>/wp-content/plugins/pressbooks/readme.txt`) and the version of WordPress from the readme.html file in the WordPress root directory (usually located at `http://<yourdomain.tld>/readme.html`). You can usually get your PHP version from your web host, or by using the [`phpversion()`](http://php.net/manual/en/function.phpversion.php) function.

**Comment by rootl** [comment]
What more information do you need? Thanks :)

**Comment by hughmcguire** [comment]
are talking about links eg, from one chapter to another within the same book?

or, from a chapter in one book to a chapter in another book?

**Comment by rootl** [comment]
Chapters and sections within the same book , sorry if it was not clear. I
asked for text samples of CSS and should have that soon.

**Comment by greatislander** [comment]
Hi @rootl, if I'm understanding correctly, the issue is:

1. You create books on one site, e.g. http://pressbooks.opensuny.org.
2. You want to be able to migrate them to another site without all the links breaking.
3. Relative links structured as `../chapter/chapter-name` do not work.

In my testing, you can get this to work by making the link go up one more level, e.g∴

`../../chapter/chapter-name`

I think this is because in a sub-directory install the levels are being parsed as follows:

| Domain | Book | Content Type | Title
------------ | ------- | ------------------ | -----
http://pressbooks.opensuny.org | bookname | chapter | chapter-1

So if you are in Chapter 1, you actually have to go up two levels:

`../` gets you to http://pressbooks.opensuny.org/bookname/chapter/, and `../../` gets you up to http://pressbooks.opensuny.org/bookname/.

Hope this helps. Also, if you want to avoid having to edit each link by hand to achieve this, we've found [this tool](https://interconnectit.com/products/search-and-replace-for-wordpress-databases/) very useful for updating paths after migrating books/networks.

**Comment by rootl** [comment]
Fantastic, thanks. I will relay this to my colleagues who are producing the
books.   That Search/Replace Script will prove very useful for folks who
don't want to do grep or any find/replace via command line  Thank you very
much!

On Wed, Mar 16, 2016 at 12:16 PM, Ned Zimmerman <notifications@github.com>
wrote:

> Closed #371 <https://github.com/pressbooks/pressbooks/issues/371>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pressbooks/pressbooks/issues/371#event-592085221>
>



-- 
Leah M Root
Library Publishing/Web Services Developer
Milne Library, SUNY Geneseo <http://www.geneseo.edu/library/leah-root>
1 College Circle, Geneseo, NY 14454
585-245-6061 | cell 585-802-4676
rootl@geneseo.edu
@RootLeah <https://twitter.com/RootLeah>

**Comment by nciske** [comment]
The Interconnect IT tool is great, but requires FTP access and knowing the path to the script to run it (plus you have to remove it afterwards as there's no authentication).

There are plugin versions similar to that script that work as well, in the WordPress admin.
https://wordpress.org/plugins/better-search-replace/

Or you could try this plugin:
https://wordpress.org/plugins/relative-url/
