### ISSUE TITLE
Question: i do not know how to start to do modifications to your child themes.

### ISSUE THREAD

**Issue by colomet** [pressbooks/pressbooks#388]
### Prerequisites

* [y ] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [ y] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ y] Are you experiencing this issue with one of our built-in root or book themes?
* [y ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

[I use one of your child theme and i want to make changes. I did in the past but now, with scss none of my changes are available in the front end.]

### Steps to Reproduce

1. [Open the fitzgerald child theme]
2. [Change the name of child theme]
2 [change the title from left to center]

**Expected behavior:** [the title is in the center]

**Actual behavior:** [the title is in the left as by default]

### Themes

Book Theme: [Enter the book theme you are using here, e.g. "fitzgerald"]

### Versions

Pressbooks: [3.3]
WordPress: [4.5]
PHP: [5.6]

You can get the version of Pressbooks from the readme.txt file in the Pressbooks plugin (usually located at `http://<yourdomain.tld>/wp-content/plugins/pressbooks/readme.txt`) and the version of WordPress from the readme.html file in the WordPress root directory (usually located at `http://<yourdomain.tld>/readme.html`). You can usually get your PHP version from your web host, or by using the [`phpversion()`](http://php.net/manual/en/function.phpversion.php) function.

**Comment by greatislander** [comment]
Did you make this change in `/theme-name/style.css/` or `/theme-name/style.scss/`? If you make the change in the `style.scss` file it will be reflected when you activate the theme, overriding the contents of `style.css`. This is not the most intuitive behaviour, and we will address it in future releases. Thanks for the report.

**Comment by colomet** [comment]
We did try that before. We did change css and scss with the same modifications and but nothing happen.

In the way it works for us is if we change in functions.php from

`function pbt_enqueue_child_theme_styles() {
    wp_enqueue_style( 'pressbooks-book);
    wp_enqueue_style( 'open-textbook);
}
)`

to

`function pbt_enqueue_child_theme_styles() {
    wp_enqueue_style( 'pressbooks-book', get_stylesheet_uri());
    wp_enqueue_style( 'open-textbook', get_stylesheet_uri());
}`

**Comment by greatislander** [comment]
I'm confused now. You are editing `functions.php` in the Pressbooks Textbook plugin, yes? Does this issue occur for you if you deactivate the Pressbooks Textbook plugin?

As a general note, @colomet, we cannot support Pressbooks Textbook-related issues here—please verify that the issue is related to Pressbooks (e.g. deactivate Pressbooks Textbook and test) before posting issues here. If you are having an issue related to Pressbooks Textbook, please post it at https://github.com/BCCampus/pressbooks-textbook.

**Comment by colomet** [comment]
First we try to do modifications with your child theme (in live), and nothing happen (now, i undestand i need to Deactivate and Activate the Child theme).  That´s why I ask to you in the first time, because i did not undestand why is not working.

For us, the purpose is to use your child theme in our own plugin. We have a specific plugin for Pressbooks where we do use some textbook funcionalities and our own funcionalities in a specific plugin for learning languages books. Before you answer us, we try to integrate the child them with our plugin and it works in that way. That´s is why I answer you with our solution. As a information of our solution. Nothing else. 

We use to try the solutions in our own way before post here. The last I want to do is disturb you wit non related questions to Pressbooks.

Here are our (Beta) developments for Pressbooks. Just in case you wish to take a look in the future. 
https://github.com/Books4Languages

Thanks for your help.

**Comment by greatislander** [comment]
Ah, okay. Thank you for clarifying. I was confused because the solution referenced PbT code so I thought maybe you had it installed.

Two things that might help:

1. I'm not clear where you are making the changes to the child theme (you were originally modifying Fitzgerald?). What I would suggest is making a new child theme, something like `pressbooks-onlingua`, which you put in `/wp-content/themes/`. Then you can follow the instructions [here](https://github.com/pressbooks/pressbooks/blob/dev/docs/themes-book.md) to make sure that all of the necessary stylesheets and resources are included.
2. See the code [here](https://github.com/pressbooks/pressbooks/blob/dev/themes-book/pressbooks-book/functions.php#L65-L78). This is the logic that determines which web stylesheets are loaded for a given theme. It works as follows:

- In all instances, line 65 loads the web stylesheet from Luther (`pressbooks-book`) so that the basic layout of the web version is present.
- If the theme is scss-based, lines 70-73 load the web stylesheet that is compiled on theme activation.
- If the theme is css-based, lines 74-79 load the included web stylesheet (`theme-name/style.css`) because there's no scss to compile.

Hope this helps—you should be able to achieve what you're looking for without that PbT code block.

**Comment by greatislander** [comment]
Also note that @bdolor removed `pbt_enqueue_child_theme_styles()` from Pressbooks Textbook in [this commit](https://github.com/BCcampus/pressbooks-textbook/commit/c880e376d7bc18a0f51617deceadf32d967e9be0), as it duplicated functionality that was included in the Pressbooks plugin (loading stylesheets twice, in other words).

**Comment by colomet** [comment]
Thanks. It really helps.
