### ISSUE TITLE
Allow custom theme options

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#470]
### Prerequisites
- [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
- [x] Are you running the [latest version of Pressbooks](http://wordpress.org/plugins/pressbooks/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
- [x] Are you experiencing this issue with one of our built-in root or book themes?
- [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?
### Description

We need to add action hooks to allow custom theme options to be added to Theme Options tabs.
### Steps to Reproduce

Not applicable.
### Themes

Book Theme: Clarke
### Versions

Pressbooks: 3.8-dev
WordPress: 4.6.1
PHP: 5.6

**Comment by bdolor** [comment]
I bumped against a related issue last week that I hope can be avoided with this ticket. There is a filter hook that was created for adding tabs `pressbooks_theme_options_tabs` https://github.com/pressbooks/pressbooks/blob/e2199ad7839518176639ecee9732bf5aa2a68aed/includes/modules/themeoptions/class-pb-themeoptions.php#L98 

A Fatal Error is encountered if you try to hook into this outside of Pressbooks, because it requires that a `\Pressbooks\` namespace function be declared. https://github.com/pressbooks/pressbooks/blob/e2199ad7839518176639ecee9732bf5aa2a68aed/includes/modules/themeoptions/class-pb-themeoptions.php#L32 

![screen shot 2016-09-12 at 10 36 21 am](https://cloud.githubusercontent.com/assets/2048170/18445945/d316b77e-78d4-11e6-9289-bbfdf5a343ab.png)

**Comment by greatislander** [comment]
@bdolor I’ve made some strides with this today (in 33baa8e). `\Pressbooks\Modules\ThemeOptions\ThemeOptions::getTabs()` and the corresponding filter now require an array like so:

```
$tabs = array(
	'global' => '\Pressbooks\Modules\ThemeOptions\GlobalOptions',
	'web' => '\Pressbooks\Modules\ThemeOptions\WebOptions',
	'pdf' => '\Pressbooks\Modules\ThemeOptions\PDFOptions',
	'mpdf' => '\Pressbooks\Modules\ThemeOptions\mPDFOptions',
	'ebook' => '\Pressbooks\Modules\ThemeOptions\EbookOptions'
);
```

The key corresponds to the `&tab=` URI parameter and the value is a fully namespaced class. Thus, a plugin can register its own tab. See here: https://gist.github.com/greatislander/8ae50058643dee4f98fe25268ec2b231
