### ISSUE TITLE
pararaph tags are indented in editor leading to strange look of paragraph tags:

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks#551]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description
pararaph tags are indented in edit
![p](https://cloud.githubusercontent.com/assets/3658808/20648047/a8ce6382-b49c-11e6-880e-9293b1bb7ed8.jpg)
![p p](https://cloud.githubusercontent.com/assets/3658808/20648046/a8ce0d06-b49c-11e6-83ab-5b9c2a65268a.jpg)

or leading to strange look of paragraph tags:

the first p-tag has this style:
p {
    margin-bottom: 0;
    text-align: initial;
}

consecutive  p-tags have indented style:
p + p, .indent {
    margin-top: 0;
    text-indent: 2em;
}

**Comment by greatislander** [comment]
Please include the book theme with any reports of this nature so that I can classify them properly.

This does look odd with a single word per paragraph, but in normal use it looks the way it should:

![screen shot 2016-11-27 at 4 24 19 pm](https://cloud.githubusercontent.com/assets/605361/20651556/1baa78ca-b4be-11e6-9041-5d809495e73a.png)

The theme you are using (I'm using Luther above, but this is true for a number of our themes) is designed to leave the first paragraph flush left and to indent subsequent paragraphs. That layout is consequently reflected in the editor display.
