### ISSUE TITLE
Delete account feature

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#846]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Users should be able to delete their accounts. Like #845, this action should be reversible for up to 30 days with network administrator's assistance. 

### Steps to Reproduce

1. From **Your Profile**, click **Delete My Account**.
2. Enter your username on the interstitial page, then click to confirm deletion.

**Expected behavior:** User account is set inactive status (how?), any books **under sole control** of the user are set to `deleted` status. After 30 days the user account is deleted, book tables are dropped and book uploads directories are erased.

### System Information

Pressbooks: 4.0
WordPress: 4.8
PHP: 7.1

**Comment by zwhpressbooks** [comment]
Issue of books with multiple admins came up here as well, and I see you've mentioned it. Books with multiple admins could either be automatically assigned to someone else, or the user could be prompted to contact their network admin(/support).

**Comment by greatislander** [comment]
I think for books with multiple _admins_ then they don't get touched and the user will just be removed. However, if the user is the admin of a book that has other user (e.g. editors/authors) without admin privileges, I think we would prompt them to assign one of the others as an administrator so the book doesn't get orphaned. This is similar behaviour to what happens when you delete a user in "normal" WP: you are prompted for another user to whom you should assign their posts.

**Comment by greatislander** [comment]
Example: https://cl.ly/310X0r3y1H3v

**Comment by zwhpressbooks** [comment]
Agreed! I have been through that process a couple of times.

**Comment by hughmcguire** [comment]
good to go @greatislander, over to the priority list

**Comment by connerbw** [comment]
### Spec

Current WP delete user functionality:

 + Remove from site, but leave association to posts
 + Remove from site, and reassign posts
 + Delete from network, and reassign posts
 + Delete from network, and delete all posts

This GitHub ticket is more or less describing: Delete from network, and reassign posts

Actually, it's:

 + For each book user is a member of:
   + If user is admin of book and is the only contributor of a book then delete book
   + Else reassign posts
+ Delete user

The glitch is with `Else reassign posts` 

Right now, for admins, WP will show a "Attribute all content to" dropdown. 

For our spec, if a user is in 10 books, and 9 of them have other contributors, the user has to deal with 9 dropdowns.

Maybe we don't show them the dropdown and just simply re-assign to any other user in the book? The problem with this, if I put myself in the shoes of a user who wants to delete themselves, is that they are probably a bit angry,  reassigning content falls into copyright, we probably don't want to be making that choice for them?

### Code

There are two unused columns in the `wp_users` table: `user_status int(11)` and `deleted (tinyint/bool)`. These columns do nothing. For thise feature I propose using the `deleted` column, with a timestamp in `wp_usermeta`, and a cron that counts 30 days between now and timestamp. We have to block any user that is set to `deleted` ourselves using hooks and filters because, like i said, that column does nothing.

**Comment by hughmcguire** [comment]
see:
https://www.engagewp.com/wordpress-allow-users-delete-accounts/

**Comment by hughmcguire** [comment]
and:
https://wordpress.org/plugins/wp-delete-user-accounts/

**Comment by greatislander** [comment]
Hey @hughmcguire, that doesn't really address what we were discussing earlier.

**Comment by hughmcguire** [comment]
highly likely.

**Comment by greatislander** [comment]
Closing for now. Can reopen when it gets into a sprint.
