### ISSUE TITLE
Add custom taxonomies to API

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#851]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

It has come to my attention while working on cloning that the REST API v2 does not add custom taxonomies to our post types. We need these, particularly for cloning. Blocks #841.

See: https://github.com/pressbooks/pressbooks/blob/dev/inc/class-taxonomy.php

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 4.0.0
WordPress: 4.8
PHP: 7.1

**Comment by connerbw** [comment]
Doh.

[The docs to do it are here](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/
). 

Mostly,  `show_in_rest' => true`

The default controller is `WP_REST_Terms_Controller` which might build links in the `wp/v2` namespace instead of `pressbooks/v2` namespace. Check how  we did an [override of the Revisions class](https://github.com/pressbooks/pressbooks/blob/master/inc/api/endpoints/controller/class-revisions.php) to fix this. Then [here](https://github.com/pressbooks/pressbooks/blob/master/inc/api/namespace.php#L44), and [here](https://github.com/pressbooks/pressbooks/blob/master/inc/api/namespace.php#L93).

If you need to do more tweaks consider the `\Pressbooks\Api\Endpoints\Controller\Posts` approach _(heavy on action/filters in an attempt to remain backwards compatible.)_
