### ISSUE TITLE
Instrument Pressbooks to Produce Caliper Analytics 1.1 statements

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks#888]
### Description

We'd like to instrument Pressbooks to enable it to produce [Caliper Analytics](https://www.imsglobal.org/activity/caliper) statements that contain information about reader/learner engagement behaviors for Pressbooks titles. I've recently made a start with @lsloan on this while at an [IMS Global](https://github.com/imsglobal) hackathon. I've spoken with @hughmcguire briefly about this in the past, and we've proposed to speak about this at the Open Education conference in Anaheim in October so more will be forthcoming, but I wanted to submit this issue as a starting point for public discussion. The 1.1 specification of Caliper Analytics, primarily authored by @arwhyte, is currently in a [private GitHub repo](https://github.com/IMSGlobal/caliper-spec/blob/master/caliper.md) (available only to IMSGlobal members), but is planned for public release shortly. We're working on a branch to demonstrate this--it's very rough but up [here](https://github.com/lsloan/pressbooks/blob/caliper-session/pressbooks.php). Our goal is to begin by instrumenting Pressbooks to produce session profile information, and then reading metric profile information, and ultimately to produce annotation and assessment information produced with the Hypothes.is and H5P plugins we're using with Pressbooks.

**Comment by SteelWagstaff** [comment]
We wrote a very quick and dirty test directly in `pressbooks.php`, but our plan now that we've confirmed that we can in fact produce simple statements and send them to a Learning Record Store is create a separate class for the caliper sensor/emitter functions.

**Comment by lsloan** [comment]
It's a shame that this issue hasn't gotten more interest.  @SteelWagstaff and I developed a simple instrumentation for a Caliper SessionEvent with the LoggedIn action.  It can be seen in my fork of the pressbooks repo:

* https://github.com/lsloan/pressbooks/blob/b6ba449/pressbooks.php#L46-L89

Admittedly, it's a simple, dirty proof-of-concept.  However, I imagine that a cleaner implementation of the [Caliper Reading Profile](https://github.com/IMSGlobal/caliper-spec/blob/master/caliper-spec.md#readingProfile) would be valuable to instructors who want to know how much time a student needs to read their materials, which pages are the most popular, and a number of other questions.

@greatislander, can you explain why the issue was closed?

**Comment by connerbw** [comment]
We're using Github for bug reports since January.

We announced this in our opensource channels and no one had issues with it?

https://pressbooks.org/blog/2018/01/25/github-housekeeping/

Please move to ideas repo: https://github.com/pressbooks/ideas/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+analytics

**Comment by greatislander** [comment]
@lsloan further to what @connerbw said — high-level analytics R&D is on our just-announced Q3 roadmap: https://pressbooks.org/blog/2018/06/30/q3-roadmap-preview/#big-projects

**Comment by lsloan** [comment]
Thanks, @greatislander, for the move.  @SteelWagstaff and I didn't know there was a separate repo for ideas and feature requests.  We're happy to learn that analytics are in the plans.

@connerbw: I don't know.  Did no one have issues with it?  I can't speak for Steel, but my only involvement with Pressbooks so far was to prototype Caliper analytics emissions.  (Sadly I'm not involved more because it looks like an interesting project.  However, my organization doesn't use it very much.)  I'm not aware of the announcements about the project.

FWIW: I think at the time this issue was opened, maybe the bug vs. feature prompts weren't supported or weren't configured.
