### ISSUE TITLE
Use `Masterminds\HTML5` Instead Of `DOMDocument` With Hacks

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pressbooks#889]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [X] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing this issue with one of our built-in root or book themes?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

Pressbooks 4.1 introduces the use of [Masterminds/html5-php](https://github.com/Masterminds/html5-php) in the cloner class.  It is tolerant of many varieties of HTML, including HTML5, XHTML 1, HTML 4, and well-formed HTML 3. It's pretty great,

Elsewhere,  we use `\DOMDocument()->loadHTML()` with hacks like:

```
$utf8_hack = '<?xml version="1.0" encoding="UTF-8"?>';
$errors = libxml_get_errors(); // TODO: Handle errors gracefully
```

We should change to `Masterminds\HTML5` and remove those hacks. In most cases it's a drop in replacement. 

### Example:

[XHTML import](https://github.com/pressbooks/pressbooks/blob/dev/inc/modules/import/html/class-xhtml.php#L283), change:

	function kneadHtml( $html, $type, $domain ) {

		libxml_use_internal_errors( true );

		// Load HTMl snippet into DOMDocument using UTF-8 hack
		$utf8_hack = '<?xml version="1.0" encoding="UTF-8"?>';
		$doc = new \DOMDocument();

		$doc->loadHTML( $utf8_hack . $html );

		// Download images, change relative paths to absolute
		$doc = $this->scrapeAndKneadImages( $doc, $domain );

		// If you are storing multi-byte characters in XML, then saving the XML using saveXML() will create problems.
		// Ie. It will spit out the characters converted in encoded format. Instead do the following:
		$html = $doc->saveXML( $doc->documentElement );

		$errors = libxml_get_errors(); // TODO: Handle errors gracefully
		libxml_clear_errors();

		return $html;
	}

To:

	use Masterminds\HTML5;
	// ...
	function kneadHtml( $html, $type, $domain ) {

		$doc = new HTML5();
		$dom = $doc->loadHTML( $html );

		// Download images, change relative paths to absolute
		$doc = $this->scrapeAndKneadImages( $dom, $domain );

		// If you are storing multi-byte characters in XML, then saving the XML using saveXML() will create problems.
		// Ie. It will spit out the characters converted in encoded format. Instead do the following:
		$html = $doc->saveXML( $doc->documentElement );

		return $html;
	}

**Comment by connerbw** [comment]
In cases where we want HTML5 and not XML (XHTML) we can replace `DOMDocument()->saveXML()` with `HTML5()->saveHTML()`

<em>Note:</em> In my tests, I noticed the XHTML import brings in `<html><body>` tags. We should [strip those tags out](https://github.com/pressbooks/pressbooks/blob/dev/inc/class-cloner.php#L604).

**Comment by greatislander** [comment]
Test:

- [ ] HTML importer
- [ ] WXR importer
- [ ] EPUB importer
- [ ] EPUB exporter
- [ ] Multi-level TOC

**Comment by pressbooksapurva** [comment]
### HTML importer
Expected behaviour as described below.

Private Books: 
- Importer recognizes a specific chapter/section of a book (such as: https://clarke.textopress.com/front-matter/introduction/). 
-  When importing an entire book (such as: https://clarke.textopress.com/), the importer fails to recognize chapters and instead imports the book as one chapter. 
- Upon inspection in the Text/Organize page, the contents of both imports are: 
![Contents when importing a Book from the HTML importer](https://user-images.githubusercontent.com/28899196/29717176-2f512ee4-897c-11e7-8f5f-e17e10d7f61e.png)

Public Books:
- Importer recognizes and successfully imports a chapter/section of a book (such as: https://custom120170802200641.textopress.com/chapter/best-chapter-for-public-books/). However, the chapter title in the imported chapter includes the chapter number from the original book (chapter numbering is on for the webbook, which is probably why):
![Chapter number included in chapter title after import. Note, chapter number is not present in the original title: https://custom120170802200641.textopress.com/chapter/best-chapter-for-public-books/](https://user-images.githubusercontent.com/28899196/29717427-2344eae0-897d-11e7-9845-e2d8148a2fd9.png)
- Importer recognizes and successfully imports complete book. Resultant content is placed in one chapter in the Text/Organize page, looks pretty much like the HTML export of the book.

Random URL
- When importing from this site: http://manga.shiekasai.com/, the importer selectively chooses which content to import. The first image and initial text is imported, while the rest is not. 
- Similarly with http://www.bbc.com/news/entertainment-arts-41048050, select content and images are imported.

### WXR importer
Importer recognizes content from a WXR file, however, does not classify items by default as "Front Matter," "Chapter," "Part," or "Back Matter." Items also seem to be listed in reverse order (with backmatter items at the start and frontmatter items at the end), but content is imported correctly.

### EPUB importer
Importer recognizes headings and content from the EPUB file, however, classifies everything as a "Chapter" - including cover page, dedication, etc. Content is successfully imported.

### EPUB exporter
Lots of errors, but the file exports and opens! Multi-level TOC also works.

### Multi-level TOC
Works in webbook, PDF, EPUB, and MOBI. 💯

**Comment by connerbw** [comment]
> WXR Importer recognizes content from a WXR file, however, does not classify items by default as "Front Matter," "Chapter," "Part," or "Back Matter."

If it's a Pressbooks WXR then this should work. Vanilla WXR, less so. I would be interested in the file.

> EPUB Importer recognizes headings and content from the EPUB file, however, classifies everything as a "Chapter" - including cover page, dedication, etc. Content is successfully imported.

This is the current behaviour. It would be easy to change. We could check if an EPUB looks like it was made with Pressbooks then make guesses based on file names for each chapter. Open a new ticket for the future?

> EPUB exporter Lots of errors, but the file exports [...]

Hopefully the errors are because of bad HTML, or stuff a user should fix. If not then I'd like more info.

Thanks @pressbooksapurva

**Comment by pressbooksapurva** [comment]
> If it's a Pressbooks WXR then this should work. Vanilla WXR, less so. I would be interested in the file.

Yeah I tested a Vanilla WXR: https://custom120170802200641.textopress.com/wp-admin/admin.php?page=pb_export (The file I used is there).

> This is the current behaviour. It would be easy to change. We could check if an EPUB looks like it was made with Pressbooks then make guesses based on file names for each chapter. Open a new ticket for the future?

Sure. :) On a post-it for now, will appear in ticket form in the near future.

> Hopefully the errors are because of bad HTML, or stuff a user should fix. If not then I'd like more info.

Looks like a bunch of broken links and errors when parsing (which I assume is shitty HTML). Let me know if you want to look at the error email but don't think it is cause for alarm.
