### ISSUE TITLE
Error when a user with no books tries to use the cloner

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#913]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

When a user with no books tries to visit the cloner page, they get an error:

> Sorry, you are not allowed to access this page.

This is because our code tries to find a book that the user can access and load the cloner there. If they don't have one, it doesn't work. Note that this is probably only an issue for super admins who don't have books but have access to the root site, because a regular user with no books would be prompted to create one.

### Steps to Reproduce

1. Log in to a network where you don't have any books.
2. Click 'Clone a Book'.

**Expected behavior:** Cloner interface loads.

**Actual behavior:** Error: "Sorry, you are not allowed to access this page."

### System Information

Pressbooks: 4.2-dev
WordPress: 4.8.1
PHP: 7.1

**Comment by connerbw** [comment]
Workaround: Super admin can navigate to any book and do Clone from there.

Currently If the user is not in book mode (`Book::isBook()`), then we redirect to the user's first found book so that cloner can have all the necessary "book-ish" features we expect from a book. 

We can change the code so that, [ if super admin, and if no book, redirect to any book ]

_Count how many times I wrote book in this post and win a prize..._ 🥇
